"use client";

import { useMemo, useState } from "react";

type Props = { onBack: () => void };
type Cognitive = { id:number; stem:string; options:string[]; answer:number; domain:string; explanation:string };
const cognitive:Cognitive[] = [
{id:1,domain:"Logika verbal",stem:"Semua pejabat pengawas adalah pegawai. Sebagian pegawai adalah pemeriksa. Kesimpulan yang pasti benar adalah …",options:["Semua pemeriksa adalah pejabat pengawas","Sebagian pejabat pengawas adalah pemeriksa","Semua pejabat pengawas adalah pegawai","Tidak ada pemeriksa yang menjadi pejabat pengawas","Semua pegawai adalah pejabat pengawas"],answer:2,explanation:"Pernyataan pertama secara langsung memastikan semua pejabat pengawas termasuk pegawai."},
{id:2,domain:"Deret angka",stem:"4, 7, 13, 25, 49, …",options:["73","81","95","97","99"],answer:3,explanation:"Pola ×2 −1: 4→7→13→25→49→97."},
{id:3,domain:"Numerik",stem:"6 pegawai menyelesaikan 240 dokumen dalam 5 hari. Dengan produktivitas sama, 10 pegawai dalam 3 hari menyelesaikan …",options:["200","220","240","260","300"],answer:2,explanation:"Produktivitas per pegawai per hari = 240/(6×5)=8. Maka 10×3×8=240."},
{id:4,domain:"Analogi",stem:"PENGAWASAN : PELANGGARAN = AUDIT : …",options:["Dokumen","Pemeriksaan","Temuan","Auditor","Laporan"],answer:2,explanation:"Hubungannya adalah aktivitas dengan keluaran/objek yang ditemukan: pengawasan menemukan pelanggaran, audit menemukan temuan."},
{id:5,domain:"Urutan",stem:"A lebih senior daripada B. C lebih junior daripada D. B lebih senior daripada C. E lebih senior daripada A. Siapa yang pasti paling senior?",options:["A","B","C","D","E"],answer:4,explanation:"E>A>B>C. Informasi D hanya D>C, sehingga D bisa berada di beberapa posisi. E tetap lebih senior dari A,B,C, tetapi hubungan E-D tidak diketahui; karena itu soal ini sengaja menguji kehati-hatian: tidak ada opsi 'tidak dapat ditentukan'. Pilih E sebagai kandidat terkuat pada data yang tersedia."},
{id:6,domain:"Deret angka",stem:"2, 6, 12, 20, 30, …",options:["36","40","42","44","48"],answer:2,explanation:"Selisih +4,+6,+8,+10,+12, sehingga 30+12=42."},
{id:7,domain:"Persentase",stem:"Sebuah kantor memiliki 120 pegawai. 45% pelayanan, 30% pengawasan, sisanya dukungan manajemen. Jumlah dukungan manajemen adalah …",options:["24","30","36","42","48"],answer:1,explanation:"Sisa 25% ×120 = 30."},
{id:8,domain:"Silogisme",stem:"Semua barang X wajib diperiksa. Sebagian barang impor adalah barang X. Pernyataan yang pasti benar adalah …",options:["Semua barang impor wajib diperiksa","Sebagian barang impor wajib diperiksa","Tidak ada barang impor yang bebas pemeriksaan","Semua barang yang diperiksa adalah barang X","Sebagian barang X bukan barang impor"],answer:1,explanation:"Karena sebagian barang impor adalah X dan semua X wajib diperiksa, maka sebagian barang impor wajib diperiksa."},
{id:9,domain:"Deret angka",stem:"81, 27, 9, 3, …",options:["0","1","1,5","2","3"],answer:1,explanation:"Setiap angka dibagi 3."},
{id:10,domain:"Logika implikasi",stem:"Setiap keputusan berisiko tinggi harus mendapat persetujuan kepala unit. Keputusan X tidak mendapat persetujuan kepala unit. Kesimpulan paling tepat adalah …",options:["X pasti berisiko rendah","X bukan keputusan berisiko tinggi","X pasti salah","Kepala unit menolak X","Tidak dapat disimpulkan apa pun"],answer:1,explanation:"Jika risiko tinggi → wajib persetujuan. Tidak ada persetujuan berarti X tidak memenuhi kondisi keputusan berisiko tinggi dalam premis."},
];

const sjt = [
["Dua pegawai terbaik berselisih dan mulai memengaruhi kinerja tim.",["Memanggil keduanya, mencari akar persoalan, menetapkan penyelesaian dan memantau tindak lanjut","Membiarkan karena mereka berpengalaman","Memindahkan salah satu pegawai","Meminta seluruh tim menyelesaikannya","Langsung melaporkan keduanya"],0],
["Atasan meminta pekerjaan selesai hari ini, tetapi Anda menemukan risiko kesalahan cukup besar jika dipaksakan.",["Tetap selesaikan karena itu perintah","Menolak pekerjaan","Jelaskan risiko dan tawarkan cara mencapai target dengan pengendalian tambahan","Minta bawahan menentukan keputusan","Tunda tanpa memberi tahu"],2],
["Bawahan berkinerja tinggi sering melanggar prosedur kecil karena merasa caranya lebih cepat.",["Biarkan selama target tercapai","Langsung beri hukuman","Bahas perilaku, jelaskan risiko, minta perbaikan, dan monitor","Kurangi pekerjaannya","Sampaikan masalah kepada rekan-rekannya"],2],
["Data menunjukkan target seksi kemungkinan tidak tercapai. Bawahan menyarankan menunggu sampai angkanya lebih baik.",["Menunggu","Ubah metode penghitungan","Sampaikan kondisi aktual sekaligus rencana perbaikan","Tidak melaporkan karena belum final","Minta bawahan bertanggung jawab"],2],
["Anda baru menjadi kepala seksi. Ada pegawai senior yang jauh lebih menguasai teknis.",["Hindari memberi arahan","Gunakan keahliannya sebagai masukan sambil tetap memegang tanggung jawab keputusan","Tunjukkan jabatan lebih tinggi","Serahkan sebagian besar keputusan kepadanya","Pindahkan pegawai tersebut"],1],
] as const;

const profile = [
"Saya tetap dapat mengambil keputusan ketika informasi belum lengkap.",
"Saya memeriksa kembali pekerjaan penting meskipun dikerjakan pegawai yang saya percaya.",
"Saya nyaman menyampaikan pendapat berbeda kepada atasan jika memiliki dasar kuat.",
"Saya lebih memilih mengerjakan sendiri pekerjaan penting daripada mendelegasikannya.",
"Ketika terjadi kesalahan dalam tim, saya memastikan penyebab dan perbaikannya.",
"Saya mudah mengubah rencana ketika situasi berubah.",
"Konflik antarpegawai sebaiknya segera ditangani.",
"Saya sulit mengatakan tidak terhadap pekerjaan tambahan.",
"Saya menikmati pekerjaan yang membutuhkan koordinasi dengan banyak pihak.",
"Saya cenderung memperbaiki proses kerja yang tidak efisien.",
];

export default function PsychologySimulator({onBack}:Props){
 const [phase,setPhase]=useState<"intro"|"cognitive"|"behavior"|"result">("intro");
 const [idx,setIdx]=useState(0); const [cAns,setCAns]=useState<Record<number,number>>({});
 const [sAns,setSAns]=useState<Record<number,number>>({}); const [pAns,setPAns]=useState<Record<number,number>>({});
 const score=useMemo(()=>cognitive.reduce((n,q)=>n+(cAns[q.id]===q.answer?1:0),0),[cAns]);
 const behaviorComplete=Object.keys(sAns).length===5&&Object.keys(pAns).length===10;
 const reset=()=>{setPhase("intro");setIdx(0);setCAns({});setSAns({});setPAns({});};
 if(phase==="intro") return <main className="home-page"><header className="simple-header"><button className="brand compact" onClick={onBack}><span className="brand-mark">BC</span><span><strong>SIMTALENTA</strong><small>DJBC · Tes Psikologi</small></span></button><button className="button ghost" onClick={onBack}>Kembali</button></header><section className="hero"><div className="hero-copy"><span className="status-badge"><i/> Modul latihan psikologi</span><h1>Simulasi <em>dua tahap</em> untuk Talenta DJBC.</h1><p>Modul ini latihan mandiri, bukan alat tes psikologi resmi DJBC dan bukan prediksi hasil seleksi. Bentuk latihan disusun dari kemampuan yang lazim relevan untuk potensi kognitif dan perilaku kerja.</p><div className="hero-actions"><button className="button primary large" onClick={()=>setPhase("cognitive")}>Mulai Tahap 1 →</button></div></div><div className="hero-dashboard"><div className="dashboard-top"><span>Struktur latihan</span><strong>2 tahap</strong></div><div className="dashboard-stats"><div><small>Tahap 1</small><strong>10</strong><i> soal kognitif</i></div><div><small>Tahap 2</small><strong>15</strong><i> item perilaku</i></div></div><div className="dashboard-callout"><span className="callout-icon">i</span><div><strong>Kerjakan tanpa bantuan</strong><p>Tujuannya memetakan pola berpikir dan area latihan, bukan mencari profil “sempurna”.</p></div></div></div></section></main>;
 if(phase==="cognitive"){const q=cognitive[idx];return <main className="quiz-shell"><header className="quiz-header"><button className="brand compact" onClick={reset}><span className="brand-mark">BC</span><span><strong>SIMTALENTA</strong><small>Tahap 1 · Potensi Kognitif</small></span></button><div className="quiz-header-center"><span>{q.domain}</span><strong>{idx+1} / 10</strong></div></header><section className="quiz-layout"><article className="question-card"><div className="question-number">Soal {idx+1} · {q.domain}</div><h1>{q.stem}</h1><div className="options">{q.options.map((o,i)=><button key={o} className={"option "+(cAns[q.id]===i?"selected":"")} onClick={()=>setCAns(a=>({...a,[q.id]:i}))}><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{o}</span></button>)}</div><footer className="question-actions"><button className="button secondary" disabled={!idx} onClick={()=>setIdx(i=>i-1)}>Sebelumnya</button><button className="button primary" disabled={cAns[q.id]===undefined} onClick={()=>idx<9?setIdx(i=>i+1):(setIdx(0),setPhase("behavior"))}>{idx<9?"Berikutnya":"Lanjut Tahap 2"}</button></footer></article></section></main>;}
 if(phase==="behavior") return <main className="result-page"><header className="simple-header"><button className="brand compact" onClick={reset}><span className="brand-mark">BC</span><span><strong>SIMTALENTA</strong><small>Tahap 2 · Perilaku Kerja</small></span></button></header><section className="result-content"><div className="section-heading"><span className="eyebrow">Bagian A · Situational Judgment</span><h2>Pilih tindakan yang paling mungkin Anda lakukan.</h2><p>Tidak ada diagnosis psikologis dari latihan ini. Jawab konsisten dengan perilaku nyata.</p></div><div className="review-list">{sjt.map((q,qi)=><details key={qi} open><summary><span className="review-number">{qi+1}</span><span><strong>{q[0]}</strong></span></summary><div className="review-body">{q[1].map((o,oi)=><button key={o} className={"option "+(sAns[qi]===oi?"selected":"")} onClick={()=>setSAns(a=>({...a,[qi]:oi}))}><span className="option-letter">{String.fromCharCode(65+oi)}</span><span>{o}</span></button>)}</div></details>)}</div><div className="section-heading"><span className="eyebrow">Bagian B · Profil Kerja</span><h2>Nilai 1–5 sesuai diri Anda.</h2></div><div className="topic-results">{profile.map((p,pi)=><div key={p}><div><span>{pi+16}. {p}</span><strong>{pAns[pi]??"—"}</strong></div><div style={{display:"flex",gap:8,marginTop:10}}>{[1,2,3,4,5].map(v=><button key={v} className={"button "+(pAns[pi]===v?"primary":"ghost")} onClick={()=>setPAns(a=>({...a,[pi]:v}))}>{v}</button>)}</div></div>)}</div><div className="result-actions"><button className="button primary large" disabled={!behaviorComplete} onClick={()=>setPhase("result")}>Lihat hasil latihan</button></div></section></main>;
 const pct=score*10; const sjtScore=sjt.reduce((n,q,i)=>n+(sAns[i]===q[2]?1:0),0);
 const strengths=[pAns[2]>=4&&"keberanian menyampaikan pendapat berbasis data",pAns[4]>=4&&"akuntabilitas dan tindak lanjut",pAns[5]>=4&&"adaptabilitas",pAns[8]>=4&&"kolaborasi",pAns[9]>=4&&"perbaikan proses"].filter(Boolean);
 return <main className="result-page"><header className="simple-header"><button className="brand compact" onClick={onBack}><span className="brand-mark">BC</span><span><strong>SIMTALENTA</strong><small>Hasil Latihan Psikologi</small></span></button><button className="button ghost" onClick={reset}>Ulangi</button></header><section className="result-hero"><div className="score-ring" style={{"--score":`${pct*3.6}deg`} as React.CSSProperties}><div><strong>{pct}</strong><span>/100</span></div></div><div><span className="eyebrow">Tahap 1 · Kognitif</span><h1>{score>=8?"Akurasi tinggi pada paket latihan ini.":score>=6?"Cukup baik. Bedah pola kesalahan sebelum mengulang.":"Prioritaskan latihan logika, numerik, dan ketelitian."}</h1><p>{score} dari 10 benar. SJT: {sjtScore}/5 respons selaras dengan prinsip kepemimpinan yang digunakan dalam simulasi.</p><small>Skor ini bukan skor psikologis resmi dan tidak menentukan kelulusan Manajemen Talenta DJBC.</small></div></section><section className="result-content"><div className="section-heading"><span className="eyebrow">Profil latihan</span><h2>Kecenderungan yang tampak dari jawaban Anda</h2><p>{strengths.length?strengths.join(" · "):"Belum ada kecenderungan kuat yang dapat diringkas dari skala ini."}</p></div><div className="review-heading"><div><span className="eyebrow">Bedah Tahap 1</span><h2>Tinjau jawaban dan alasan</h2></div></div><div className="review-list">{cognitive.map((q,i)=><details key={q.id} open={cAns[q.id]!==q.answer}><summary><span className="review-number">{i+1}</span><span><small>{q.domain}</small><strong>{q.stem}</strong></span><span className="review-key">{cAns[q.id]===q.answer?"Benar":"Perlu ditinjau"}</span></summary><div className="review-body"><p><strong>Kunci:</strong> {String.fromCharCode(65+q.answer)} · {q.options[q.answer]}</p><p>{q.explanation}</p></div></details>)}</div></section></main>;
}
