export type Topic =
  | "Manajemen Kinerja"
  | "Disiplin & Kepegawaian"
  | "PPID"
  | "Komunikasi & Penyuluhan"
  | "Kepatuhan Internal"
  | "Organisasi, Sejarah & Logo"
  | "Umum, Rumah Tangga & BMN"
  | "Keuangan & Pengadaan";

export type Difficulty = "Dasar" | "Analitik" | "Menjebak";
export type QuizOption = readonly [text: string, explanation: string];

export type Question = {
  id: number;
  topic: Topic;
  difficulty: Difficulty;
  stem: string;
  options: readonly QuizOption[];
  answer: number;
  source: keyof typeof sources;
  reference: string;
};

export const sources = {
  kmk127: {
    label: "KMK 127 Tahun 2026 — Manajemen Kinerja",
    url: "https://drive.google.com/file/d/1jxbHqKcSD7ypahCvBcb8BgxAvR_ZCsiI/view",
  },
  sosKinerja: {
    label: "Sosialisasi Manajemen Kinerja KMK 127/2026",
    url: "https://drive.google.com/file/d/17pCsQgxKH4PGgovXGd6b1RztMC9cyKAF/view",
  },
  disiplin: {
    label: "Bimtek Pemeriksaan dan Penjatuhan Hukuman Disiplin, Itjen Kemenkeu 2026",
    url: "https://drive.google.com/file/d/1dQLpk2O-p_W8SxNoBjaAWZ9a47ekORig/view",
  },
  pp94: {
    label: "PP 94 Tahun 2021 tentang Disiplin PNS — JDIH BKN",
    url: "https://jdih.bkn.go.id/Detail_peraturan/breaking/2537",
  },
  ppid: {
    label: "PMK 110/PMK.01/2022 — Pedoman Layanan Informasi Publik",
    url: "https://drive.google.com/file/d/1fuzKMZW1ICj1kt3enpcVP4kweN7XS1G3/view",
  },
  uuKip: {
    label: "UU 14 Tahun 2008 tentang Keterbukaan Informasi Publik",
    url: "https://drive.google.com/file/d/14DH721LnIZv8oa1F6zpWOVrJVEBt5Q8c/view",
  },
  perki: {
    label: "PerKI 1 Tahun 2021 — Standar Layanan Informasi Publik",
    url: "https://drive.google.com/file/d/1iC2zkI_nhEqGmdypBoj56zdc48LmFSua/view",
  },
  se15: {
    label: "SE-15/BC/2025 — Pemberian dan Layanan Informasi DJBC",
    url: "https://drive.google.com/file/d/1V31w7_BRSAfdhmqTEvkZQ22eO46Kqldk/view",
  },
  se14: {
    label: "SE-14/BC/2025 — Komunikasi Internal DJBC",
    url: "https://drive.google.com/file/d/1ZATZ9vZw2PGSo7r7NskU2MkDsSkl2hyj/view",
  },
  komunikasi: {
    label: "KMK 342 Tahun 2025 — Pedoman Pengelolaan Komunikasi Kemenkeu",
    url: "https://drive.google.com/file/d/1qJQQpE93G5Ux_EKjmSJH8fVDf7OJd7pK/view",
  },
  uki: {
    label: "Materi Tugas dan Fungsi UKI DJBC",
    url: "https://docs.google.com/presentation/d/1i0uBbYekqDf2zVSNNqfrgEj864y_Q9PX/edit",
  },
  organisasi: {
    label: "Semua Tentang Bea Cukai — pembaruan Desember 2025",
    url: "https://drive.google.com/file/d/1F-2tFGm65n981KMF0smPNg2hZPnNkJ3U/view",
  },
  tnd: {
    label: "PMK 164/PMK.01/2021 — Pedoman Tata Naskah Dinas",
    url: "https://jdih.kemenkeu.go.id/dok/164-pmk-01-2021/summary",
  },
  bmn40: {
    label: "PMK 40 Tahun 2024 — Tata Cara Penggunaan BMN",
    url: "https://jdih.kemenkeu.go.id/dok/pmk-40-tahun-2024/summary",
  },
  bmn120: {
    label: "PMK 120 Tahun 2024 — Pengelolaan BMN yang Tidak Digunakan",
    url: "https://jdih.kemenkeu.go.id/dok/pmk-120-tahun-2024/files",
  },
  bmn138: {
    label: "PMK 138 Tahun 2024 — Standar Barang dan Standar Kebutuhan BMN",
    url: "https://www.jdih.kemenkeu.go.id/dok/pmk-138-tahun-2024/summary",
  },
  otk: {
    label: "PMK 124 Tahun 2024 jo. PMK 117 Tahun 2025 — OTK Kemenkeu",
    url: "https://jdih.kemenkeu.go.id/dok/pmk-117-tahun-2025",
  },
  anggaran: {
    label: "PMK 62 Tahun 2023 jo. PMK 41 Tahun 2026",
    url: "https://jdih.kemenkeu.go.id/dok/pmk-41-tahun-2026",
  },
  sbm: {
    label: "PMK 32 Tahun 2025 — Standar Biaya Masukan TA 2026",
    url: "https://jdih.kemenkeu.go.id/dok/pmk-32-tahun-2025/overview",
  },
  ssb: {
    label: "PMK 79 Tahun 2025 — Standar Struktur Biaya",
    url: "https://jdih.kemenkeu.go.id/dok/pmk-79-tahun-2025",
  },
  perdin: {
    label: "PMK 113/PMK.05/2012 jo. PMK 119 Tahun 2023 — Perjalanan Dinas",
    url: "https://jdih.kemenkeu.go.id/dok/pmk-119-tahun-2023/summary",
  },
  pbj: {
    label: "Perpres 16 Tahun 2018 jo. Perpres 46 Tahun 2025 — PBJ Pemerintah",
    url: "https://jdih.lkpp.go.id/regulation/peraturan-presiden/peraturan-presiden-nomor-46-tahun-2025",
  },
} as const;

export const questions: Question[] = [
  {
    id: 1,
    topic: "Manajemen Kinerja",
    difficulty: "Analitik",
    stem: "Seorang pegawai dalam tim kolaboratif menganggap Dialog Kinerja Individu (DKI) hanya diperlukan saat penyusunan SKP. Penilaian yang paling tepat adalah…",
    options: [
      ["Tepat, karena DKI berakhir setelah SKP disepakati.", "Keliru. DKI mencakup seluruh siklus, bukan hanya perencanaan SKP."],
      ["Tidak tepat; DKI juga mencakup pelaksanaan, evaluasi, dan tindak lanjut serta dapat melibatkan ketua tim.", "Benar. DKI adalah media komunikasi berkelanjutan; pada kerja kolaboratif dapat dilakukan bersama ketua tim/atasan unit penugasan."],
      ["Tepat, kecuali pegawai tersebut pejabat fungsional.", "Keliru. Cakupan DKI tidak dibatasi hanya berdasarkan jenis jabatan."],
      ["Tidak tepat, tetapi DKI hanya boleh dilakukan oleh pengelola kinerja.", "Keliru. Pihak utamanya adalah Pejabat Penilai Kinerja dan pegawai, dengan pihak relevan pada penugasan kolaboratif."],
    ],
    answer: 1,
    source: "kmk127",
    reference: "Lampiran II — Pelaksanaan Kinerja Pegawai, Dialog Kinerja Individu",
  },
  {
    id: 2,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "DKI dapat dilakukan insidental atau bulanan/triwulanan. Batas minimum pelaporannya adalah…",
    options: [
      ["Sekali setiap bulan.", "Keliru. Bulanan adalah salah satu frekuensi pelaksanaan, bukan minimum pelaporan."],
      ["Sekali setiap semester.", "Keliru. Jangka ini lebih lama daripada batas yang ditetapkan."],
      ["Paling sedikit sekali dalam tiga bulan.", "Benar. DKI dilaporkan paling sedikit satu kali dalam tiga bulan."],
      ["Hanya pada akhir tahun.", "Keliru. DKI dimaksudkan menjadi komunikasi kinerja berkelanjutan."],
    ],
    answer: 2,
    source: "kmk127",
    reference: "Lampiran II — frekuensi dan pelaporan DKI",
  },
  {
    id: 3,
    topic: "Manajemen Kinerja",
    difficulty: "Dasar",
    stem: "Kombinasi yang paling lengkap menggambarkan muatan SKP adalah…",
    options: [
      ["Hasil Kerja, Perilaku Kerja, dan Lampiran SKP.", "Benar. Ketiganya merupakan kelompok muatan SKP dalam KMK 127/2026."],
      ["IKU, NKO, dan laporan keuangan.", "Keliru. IKU/NKO dominan pada kinerja organisasi; laporan keuangan bukan kelompok muatan SKP."],
      ["Hasil Kerja Utama saja.", "Keliru. SKP juga memuat perilaku dan lampiran pendukung."],
      ["Perilaku Kerja dan hukuman disiplin saja.", "Keliru. Hukuman disiplin memengaruhi evaluasi; bukan pengganti komponen hasil kerja."],
    ],
    answer: 0,
    source: "kmk127",
    reference: "Lampiran II — Perencanaan SKP",
  },
  {
    id: 4,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Dalam penghitungan awal kinerja pegawai, bobot NHK dan NPK yang benar adalah…",
    options: [
      ["NHK 60% dan NPK 40%.", "Keliru. Komposisi ini tidak digunakan pada KMK 127/2026."],
      ["NHK 70% dan NPK 30%.", "Keliru. Angka 70/30 muncul dalam konteks bobot NKO tertentu, bukan bobot NHK–NPK."],
      ["NHK 80% dan NPK 20%.", "Keliru. Hasil kerja memang dominan, tetapi bukan dengan komposisi ini."],
      ["NHK 75% dan NPK 25%.", "Benar. Nilai Hasil Kerja berbobot 75% dan Nilai Perilaku Kerja 25%."],
    ],
    answer: 3,
    source: "sosKinerja",
    reference: "Improvement Penghitungan Nilai Kinerja Pegawai",
  },
  {
    id: 5,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Pasangan batas maksimum NHK/NPK menurut kelompok jabatan yang tepat adalah…",
    options: [
      ["120 untuk semua pegawai.", "Keliru. Batas 120 hanya berlaku pada kelompok jabatan tertentu."],
      ["120 untuk Menteri/Wakil Menteri/JPT Madya; 115 untuk JPT Pratama, Administrator, Pengawas, JF, dan Pelaksana.", "Benar. Materi sosialisasi membedakan batas maksimum menjadi 120 dan 115 menurut kelompok jabatan."],
      ["115 untuk Menteri/Wakil Menteri; 120 untuk Pelaksana.", "Keliru. Pasangan ini terbalik."],
      ["100 untuk seluruh jabatan agar seragam.", "Keliru. KMK memungkinkan capaian di atas 100 dengan batas berbeda."],
    ],
    answer: 1,
    source: "sosKinerja",
    reference: "Batas maksimum NHK dan NPK",
  },
  {
    id: 6,
    topic: "Manajemen Kinerja",
    difficulty: "Analitik",
    stem: "Mengapa seluruh IKU/IKI diwajibkan memiliki trajectory target bulanan atau triwulanan?",
    options: [
      ["Agar target tahunan dapat dihapus.", "Keliru. Trajectory menurunkan target tahunan ke periode, bukan menghapusnya."],
      ["Agar nilai perilaku dapat diganti dengan capaian indikator.", "Keliru. Perilaku tetap komponen tersendiri."],
      ["Agar kinerja dapat diukur dan dievaluasi secara periodik serta dideteksi lebih dini.", "Benar. Trajectory menjadi acuan evaluasi periodik dan deteksi dini deviasi kinerja."],
      ["Agar hanya pengelola kinerja yang mengetahui target.", "Keliru. Prinsip manajemen kinerja justru partisipatif dan transparan."],
    ],
    answer: 2,
    source: "sosKinerja",
    reference: "Matriks Perubahan — trajectory target",
  },
  {
    id: 7,
    topic: "Manajemen Kinerja",
    difficulty: "Analitik",
    stem: "Reviu Kualitas Komitmen Kinerja (K3) menilai dua kelompok utama, yaitu…",
    options: [
      ["Kualitas indikator dan kualitas target.", "Benar. Indikator dilihat dari validitas/kendali, sedangkan target dibandingkan dengan data relevan sebelumnya."],
      ["Jumlah rapat dan jumlah pegawai.", "Keliru. Keduanya bukan dimensi kualitas K3."],
      ["Nilai perilaku dan jumlah hukuman disiplin.", "Keliru. Itu terkait evaluasi pegawai, bukan dua dimensi inti reviu K3."],
      ["Realisasi anggaran dan usia pegawai.", "Keliru. Usia pegawai tidak menjadi dimensi K3."],
    ],
    answer: 0,
    source: "sosKinerja",
    reference: "Reviu K3 — kualitas indikator dan target",
  },
  {
    id: 8,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Sidang Tim Penilai Kinerja (TPK) dilaksanakan secara triwulanan dan tahunan terutama untuk menentukan…",
    options: [
      ["SKP, PK, dan DIPA.", "Keliru. DIPA bukan produk Sidang TPK."],
      ["NKO saja tanpa faktor lain.", "Keliru. TPK berfokus pada nilai koreksi dan dampak tertentu."],
      ["Nilai Koreksi, Nilai Dampak Pelanggaran Disiplin, dan Nilai Dampak Perilaku.", "Benar. Ketiga nilai ini ditentukan melalui Sidang TPK untuk menjaga objektivitas dan akuntabilitas."],
      ["Kenaikan pangkat otomatis.", "Keliru. Hasil kinerja dapat dimanfaatkan dalam proses kepegawaian, tetapi TPK tidak otomatis menetapkan kenaikan pangkat."],
    ],
    answer: 2,
    source: "sosKinerja",
    reference: "Matriks Perubahan — struktur dan Sidang TPK",
  },
  {
    id: 9,
    topic: "Manajemen Kinerja",
    difficulty: "Analitik",
    stem: "Dibanding kebijakan sebelumnya, NKP pada KMK 127/2026 diperkuat karena ikut memperhitungkan…",
    options: [
      ["NHK dan NPK saja.", "Keliru. Justru kebijakan baru menambahkan beberapa komponen di luar NHK dan NPK."],
      ["NKO, Nilai Hukuman Disiplin, Nilai Dampak Pelanggaran Disiplin, dan Nilai Koreksi.", "Benar. Komponen tersebut menghubungkan kinerja individu, organisasi, integritas, dan fakta kinerja."],
      ["Masa kerja dan usia saja.", "Keliru. Keduanya bukan komponen formula NKP yang dimaksud."],
      ["Jumlah pelatihan tanpa melihat hasil kerja.", "Keliru. Pelatihan dapat menjadi tindak lanjut pengembangan, bukan komponen tunggal NKP."],
    ],
    answer: 1,
    source: "sosKinerja",
    reference: "Improvement Penghitungan NKP",
  },
  {
    id: 10,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Jika hasil penghitungan pegawai ≥ NKO, bobot untuk Pimpinan UPK, pegawai satu tingkat di bawahnya, dan JF substansi adalah…",
    options: [
      ["NKO 10% + hasil penghitungan 90%.", "Keliru. Komposisi 10/90 berlaku ketika hasil penghitungan berada di bawah NKO."],
      ["NKO 30% + hasil penghitungan 70%.", "Keliru. Ini untuk kelompok dua tingkat atau lebih di bawah/JF non-substansi saat hasil ≥ NKO."],
      ["NKO 70% + hasil penghitungan 30%.", "Keliru. Komposisi ini tidak digunakan pada skenario tersebut."],
      ["NKO 50% + hasil penghitungan 50%.", "Benar. Kelompok yang paling dekat dengan kinerja organisasi mendapat bobot NKO 50% pada kondisi ini."],
    ],
    answer: 3,
    source: "sosKinerja",
    reference: "Bobot persentase NKO dalam formula NKP",
  },
  {
    id: 11,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Jika hasil penghitungan pegawai ≥ NKO, bobot bagi pegawai dua tingkat atau lebih di bawah Pimpinan UPK serta JF non-substansi adalah…",
    options: [
      ["NKO 30% + hasil penghitungan 70%.", "Benar. Keterkaitan langsung dengan NKO diberi bobot lebih kecil daripada kelompok pimpinan/level dekat."],
      ["NKO 50% + hasil penghitungan 50%.", "Keliru. Ini untuk Pimpinan UPK, satu tingkat di bawah, dan JF substansi."],
      ["NKO 10% + hasil penghitungan 90%.", "Keliru. Ini digunakan ketika hasil penghitungan < NKO."],
      ["NKO 100%.", "Keliru. Kinerja individu tetap diperhitungkan."],
    ],
    answer: 0,
    source: "sosKinerja",
    reference: "Bobot persentase NKO dalam formula NKP",
  },
  {
    id: 12,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Saat hasil penghitungan pegawai lebih rendah daripada NKO, formula bobot yang digunakan adalah…",
    options: [
      ["NKO 50% + hasil 50%.", "Keliru. Formula ini berlaku pada kelompok tertentu ketika hasil ≥ NKO."],
      ["NKO 30% + hasil 70%.", "Keliru. Formula ini juga terkait kondisi hasil ≥ NKO pada kelompok tertentu."],
      ["NKO 10% + hasil 90%.", "Benar. Saat hasil individu di bawah NKO, porsi terbesar tetap berasal dari hasil penghitungan individu."],
      ["NKO 90% + hasil 10%.", "Keliru. Komposisinya terbalik."],
    ],
    answer: 2,
    source: "sosKinerja",
    reference: "Bobot NKO ketika hasil penghitungan < NKO",
  },
  {
    id: 13,
    topic: "Manajemen Kinerja",
    difficulty: "Dasar",
    stem: "Evaluasi perilaku kerja dengan pendekatan 360° paling tepat melibatkan…",
    options: [
      ["Atasan langsung saja.", "Keliru. Atasan merupakan salah satu evaluator, bukan satu-satunya."],
      ["Rekan kerja saja.", "Keliru. Peers hanya salah satu sudut pandang."],
      ["Atasan, rekan kerja, dan/atau anggota/bawahan yang relevan.", "Benar. Pendekatan 360° menggabungkan pengamatan dari relasi kerja yang berbeda."],
      ["Pengguna jasa eksternal saja.", "Keliru. Instrumen utama menyebut atasan, peers, dan/atau anggota/bawahan."],
    ],
    answer: 2,
    source: "kmk127",
    reference: "Lampiran II — evaluator perilaku kerja",
  },
  {
    id: 14,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Manakah yang bukan bagian dari nilai dasar ASN/aspek instrumen perilaku yang disebut dalam KMK 127/2026?",
    options: [
      ["Berorientasi Pelayanan.", "Keliru sebagai jawaban karena aspek ini memang dinilai."],
      ["Adaptif.", "Keliru sebagai jawaban karena Adaptif termasuk nilai dasar ASN."],
      ["Kompetitif Individual.", "Benar sebagai pilihan 'bukan'. Istilah ini tidak termasuk BerAKHLAK maupun aspek Kepemimpinan."],
      ["Kepemimpinan.", "Keliru sebagai jawaban karena aspek Kepemimpinan turut disebut dalam instrumen."],
    ],
    answer: 2,
    source: "kmk127",
    reference: "Lampiran II — instrumen evaluasi perilaku kerja",
  },
  {
    id: 15,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Manual IKI disusun paling lambat…",
    options: [
      ["Satu bulan setelah SKP ditetapkan dan sebelum masa reviu K3 periode berakhir.", "Benar. Kedua batas ini harus diperhatikan bersamaan."],
      ["Pada akhir tahun setelah seluruh realisasi diketahui.", "Keliru. Manual diperlukan sejak awal sebagai acuan pengukuran."],
      ["Tiga bulan setelah evaluasi tahunan.", "Keliru. Waktunya terlalu lambat dan tidak sesuai ketentuan."],
      ["Hanya jika capaian IKI di bawah target.", "Keliru. Manual IKI bukan dokumen korektif opsional."],
    ],
    answer: 0,
    source: "kmk127",
    reference: "Lampiran II — penyusunan manual IKI",
  },
  {
    id: 16,
    topic: "Manajemen Kinerja",
    difficulty: "Analitik",
    stem: "Pegawai ditugaskan penuh waktu dalam squad team. Tata kelola kinerja yang paling tepat adalah…",
    options: [
      ["SKP ditiadakan karena pegawai bekerja lintas unit.", "Keliru. Penugasan lintas unit tetap harus diterjemahkan ke SKP/IKI."],
      ["Dialog hanya dengan ketua tim; atasan definitif tidak perlu tahu.", "Keliru. Kesepakatan juga disampaikan kepada atasan langsung definitif."],
      ["Dialog bersama atasan definitif dan pemilik kinerja/ketua tim, dengan minimal satu IKI sesuai output/outcome penugasan.", "Benar. Ini menjaga keselarasan penugasan dan pertanggungjawaban definitif."],
      ["Cukup mencatat perilaku kerja tanpa hasil kerja.", "Keliru. Hasil kerja penugasan harus terukur melalui IKI."],
    ],
    answer: 2,
    source: "kmk127",
    reference: "Lampiran II — Squad Team/Tim Kerja Penuh Waktu",
  },
  {
    id: 17,
    topic: "Manajemen Kinerja",
    difficulty: "Dasar",
    stem: "Perbedaan pokok evaluasi kinerja periodik dan tahunan adalah…",
    options: [
      ["Periodik dilakukan setiap periode tertentu; tahunan merekap satu tahun kinerja.", "Benar. Evaluasi periodik dapat bulanan/triwulanan, sedangkan tahunan mencakup periode tahunan."],
      ["Periodik hanya untuk pimpinan; tahunan hanya untuk pelaksana.", "Keliru. Pembedanya waktu, bukan semata jenjang jabatan."],
      ["Periodik menilai perilaku; tahunan hanya hasil kerja.", "Keliru. Keduanya dapat mencakup elemen hasil dan perilaku sesuai mekanisme."],
      ["Tidak ada perbedaan.", "Keliru. KMK secara eksplisit membedakan waktu pelaksanaan evaluasi."],
    ],
    answer: 0,
    source: "kmk127",
    reference: "Lampiran II — waktu pelaksanaan evaluasi",
  },
  {
    id: 18,
    topic: "Manajemen Kinerja",
    difficulty: "Menjebak",
    stem: "Pasangan keluaran evaluasi yang tepat adalah…",
    options: [
      ["Organisasi: NKP; Pegawai: NKO.", "Keliru. Istilahnya tertukar."],
      ["Organisasi: NKO dan Predikat NKO; Pegawai: NKP dan Predikat Kinerja Pegawai.", "Benar. NKO untuk organisasi dan NKP untuk pegawai, masing-masing disertai predikat."],
      ["Organisasi: SKP; Pegawai: PK.", "Keliru. SKP/PK adalah dokumen perencanaan, bukan keluaran akhir evaluasi tersebut."],
      ["Organisasi dan pegawai: hanya nilai tanpa predikat.", "Keliru. Predikat juga merupakan keluaran."],
    ],
    answer: 1,
    source: "kmk127",
    reference: "Diktum KEDUAPULUHSATU",
  },
  {
    id: 19,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Dasar",
    stem: "Regulasi utama disiplin PNS yang menggantikan PP 53 Tahun 2010 adalah…",
    options: [
      ["PP 94 Tahun 2021.", "Benar. PP 94/2021 merupakan ketentuan disiplin PNS yang berlaku dan menggantikan PP 53/2010."],
      ["PP 11 Tahun 2017.", "Keliru. PP 11/2017 mengatur Manajemen PNS secara lebih luas."],
      ["PP 79 Tahun 2021.", "Keliru. PP 79/2021 mengatur upaya administratif dan BPASN."],
      ["PMK 164 Tahun 2021.", "Keliru. PMK ini mengatur Tata Naskah Dinas Kemenkeu."],
    ],
    answer: 0,
    source: "pp94",
    reference: "Status dan dasar hukum Disiplin PNS",
  },
  {
    id: 20,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "Manakah yang termasuk jenis hukuman disiplin ringan?",
    options: [
      ["Pemotongan tunjangan kinerja 25% selama 6 bulan.", "Keliru. Ini termasuk hukuman disiplin sedang."],
      ["Penurunan jabatan setingkat lebih rendah selama 12 bulan.", "Keliru. Ini hukuman disiplin berat."],
      ["Teguran lisan, teguran tertulis, atau pernyataan tidak puas secara tertulis.", "Benar. Ketiganya merupakan jenis hukuman disiplin ringan."],
      ["Pemberhentian dengan hormat tidak atas permintaan sendiri.", "Keliru. Ini hukuman disiplin berat."],
    ],
    answer: 2,
    source: "pp94",
    reference: "Pasal 8 — tingkat dan jenis hukuman disiplin",
  },
  {
    id: 21,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "Pola hukuman disiplin sedang dalam PP 94/2021 adalah…",
    options: [
      ["Pemotongan tunjangan kinerja 25% selama 6, 9, atau 12 bulan.", "Benar. Tingkat sedang dibedakan menurut lamanya pemotongan 25%."],
      ["Pemotongan gaji pokok 50% tanpa batas waktu.", "Keliru. Jenis ini tidak dirumuskan demikian dalam PP 94/2021."],
      ["Teguran lisan sampai tiga kali.", "Keliru. Teguran lisan adalah hukuman ringan."],
      ["Penjara administratif 30 hari.", "Keliru. Ini bukan jenis hukuman disiplin PNS."],
    ],
    answer: 0,
    source: "pp94",
    reference: "Pasal 8 — hukuman disiplin sedang",
  },
  {
    id: 22,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "Manakah yang bukan jenis hukuman disiplin berat menurut PP 94/2021?",
    options: [
      ["Penurunan jabatan setingkat lebih rendah selama 12 bulan.", "Keliru sebagai jawaban karena ini memang hukuman berat."],
      ["Pembebasan dari jabatan menjadi jabatan pelaksana selama 12 bulan.", "Keliru sebagai jawaban karena ini memang hukuman berat."],
      ["Pemberhentian dengan hormat tidak atas permintaan sendiri sebagai PNS.", "Keliru sebagai jawaban karena ini memang hukuman berat."],
      ["Teguran tertulis.", "Benar sebagai pilihan 'bukan'. Teguran tertulis adalah hukuman ringan."],
    ],
    answer: 3,
    source: "pp94",
    reference: "Pasal 8 — hukuman disiplin berat",
  },
  {
    id: 23,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Analitik",
    stem: "Seorang pengguna jasa memberi hadiah setelah layanan selesai dan mengaitkannya dengan jabatan pegawai. Sikap yang paling tepat adalah…",
    options: [
      ["Diterima karena layanan sudah selesai.", "Keliru. Hubungan dengan jabatan/pekerjaan tetap membuatnya terlarang."],
      ["Diterima jika nilainya kecil.", "Keliru. Larangan tidak otomatis hilang hanya karena nilai dianggap kecil."],
      ["Ditolak dan ditangani sesuai ketentuan gratifikasi karena hadiah berhubungan dengan jabatan/pekerjaan.", "Benar. PP 94 melarang menerima hadiah yang berhubungan dengan jabatan dan/atau pekerjaan."],
      ["Diterima lalu dibagi kepada tim.", "Keliru. Pembagian tidak menghapus hubungan hadiah dengan jabatan."],
    ],
    answer: 2,
    source: "disiplin",
    reference: "Larangan PNS — hadiah terkait jabatan/pekerjaan",
  },
  {
    id: 24,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Analitik",
    stem: "Yang paling tepat menggambarkan 'pungutan di luar ketentuan' adalah…",
    options: [
      ["Setiap penerimaan negara yang memiliki dasar hukum.", "Keliru. Penerimaan resmi berdasar hukum bukan pungutan di luar ketentuan."],
      ["Pengenaan biaya yang seharusnya tidak dikenakan atau penyalahgunaan wewenang untuk memperoleh uang/barang bagi diri atau pihak lain.", "Benar. Unsurnya adalah biaya tidak semestinya atau penyalahgunaan wewenang untuk keuntungan tertentu."],
      ["Pembayaran nontunai melalui kanal resmi.", "Keliru. Kanal pembayaran resmi bukan pelanggaran."],
      ["Pengembalian kelebihan pembayaran kepada pengguna jasa.", "Keliru. Pengembalian yang sah bukan pungutan."],
    ],
    answer: 1,
    source: "disiplin",
    reference: "Larangan PNS — melakukan pungutan di luar ketentuan",
  },
  {
    id: 25,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "Dalam PP 94/2021, pengertian Masuk Kerja mencakup…",
    options: [
      ["Hanya hadir secara fisik di ruang kantor.", "Keliru. Pengertiannya tidak dibatasi pada gedung kantor."],
      ["Melaksanakan tugas kedinasan, baik di dalam maupun di luar kantor.", "Benar. Fokusnya adalah pelaksanaan tugas sesuai ketentuan, bukan lokasi fisik semata."],
      ["Hanya mengisi daftar hadir elektronik.", "Keliru. Daftar hadir adalah bukti administratif, bukan keseluruhan makna Masuk Kerja."],
      ["Setiap aktivitas pribadi pada hari kerja.", "Keliru. Aktivitas harus terkait pelaksanaan tugas kedinasan."],
    ],
    answer: 1,
    source: "pp94",
    reference: "Ketentuan umum — Masuk Kerja",
  },
  {
    id: 26,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "Pegawai tidak hadir pada panggilan pemeriksaan pertama tanpa alasan sah. Langkah berikutnya adalah…",
    options: [
      ["Pemeriksaan otomatis dihentikan.", "Keliru. Ketidakhadiran tanpa alasan sah tidak menghentikan proses."],
      ["Langsung menjatuhkan hukuman tanpa panggilan kedua.", "Keliru. Mekanisme normal memberikan panggilan kedua."],
      ["Menerbitkan panggilan kedua paling lambat tujuh hari kerja sejak tanggal seharusnya hadir pada panggilan pertama.", "Benar. Panggilan kedua merupakan tahap berikut dengan interval yang ditentukan."],
      ["Menunggu satu tahun agar hak jawab pulih.", "Keliru. Tidak ada ketentuan demikian."],
    ],
    answer: 2,
    source: "disiplin",
    reference: "Alur pemeriksaan — panggilan I dan II",
  },
  {
    id: 27,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Analitik",
    stem: "Pegawai tetap tidak memenuhi panggilan pemeriksaan kedua tanpa alasan sah. Konsekuensi prosedural yang paling tepat adalah…",
    options: [
      ["Kasus dianggap tidak terbukti.", "Keliru. Ketidakhadiran tidak otomatis menghapus bukti pelanggaran."],
      ["Pejabat berwenang dapat menjatuhkan hukuman berdasarkan alat bukti dan keterangan yang ada.", "Benar. Proses dapat dilanjutkan berdasarkan bukti yang tersedia setelah kesempatan hadir diberikan."],
      ["Semua bukti harus dimusnahkan.", "Keliru. Bukti justru menjadi dasar penilaian."],
      ["Pegawai otomatis bebas dari disiplin.", "Keliru. Menghindari pemeriksaan bukan alasan pembebasan."],
    ],
    answer: 1,
    source: "pp94",
    reference: "Tata cara pemeriksaan — ketidakhadiran setelah panggilan kedua",
  },
  {
    id: 28,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Dasar",
    stem: "Prinsip pelaksanaan pemeriksaan dugaan pelanggaran disiplin adalah…",
    options: [
      ["Terbuka untuk umum agar memberi efek jera.", "Keliru. Pemeriksaan disiplin dilakukan tertutup untuk menjaga proses dan para pihak."],
      ["Tertutup dan dituangkan dalam berita acara pemeriksaan.", "Benar. Kerahasiaan proses tidak menghilangkan kewajiban dokumentasi resmi."],
      ["Tanpa dokumentasi agar fleksibel.", "Keliru. Hasil pemeriksaan harus dapat dipertanggungjawabkan."],
      ["Hanya melalui percakapan informal.", "Keliru. Pemeriksaan merupakan proses formal."],
    ],
    answer: 1,
    source: "pp94",
    reference: "Tata cara pemeriksaan disiplin",
  },
  {
    id: 29,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "Pembentukan tim pemeriksa terhadap dugaan pelanggaran yang ancamannya sedang atau berat mengikuti pola…",
    options: [
      ["Dilarang untuk semua pelanggaran.", "Keliru. Tim pemeriksa justru menjadi instrumen pemeriksaan."],
      ["Wajib untuk sedang, opsional untuk berat.", "Keliru. Polanya terbalik."],
      ["Dapat dibentuk untuk ancaman sedang dan wajib dibentuk untuk ancaman berat.", "Benar. Tingkat berat mensyaratkan jaminan pemeriksaan melalui tim."],
      ["Hanya boleh dibentuk setelah hukuman dijatuhkan.", "Keliru. Tim dibentuk untuk proses pemeriksaan sebelum keputusan."],
    ],
    answer: 2,
    source: "pp94",
    reference: "Tim Pemeriksa",
  },
  {
    id: 30,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "PNS tidak masuk kerja tanpa alasan sah secara kumulatif selama 3 hari kerja dalam satu tahun. Jenis hukuman yang sesuai adalah…",
    options: [
      ["Teguran lisan.", "Benar. Batas 3 hari kumulatif dikenai teguran lisan."],
      ["Pemotongan tunjangan 25% selama 6 bulan.", "Keliru. Ini berlaku pada rentang ketidakhadiran yang lebih tinggi."],
      ["Penurunan jabatan 12 bulan.", "Keliru. Ini hukuman berat untuk rentang yang jauh lebih tinggi."],
      ["Pemberhentian.", "Keliru. Tiga hari kumulatif belum mencapai ambang pemberhentian."],
    ],
    answer: 0,
    source: "pp94",
    reference: "Pelanggaran kewajiban masuk kerja — 3 hari kumulatif",
  },
  {
    id: 31,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "PNS tidak masuk kerja tanpa alasan sah selama 10 hari kerja berturut-turut. Konsekuensi yang paling tepat adalah…",
    options: [
      ["Teguran tertulis.", "Keliru. Pelanggaran berturut-turut ini diperlakukan jauh lebih berat."],
      ["Pemberhentian dengan hormat tidak atas permintaan sendiri sebagai PNS.", "Benar. Sepuluh hari berturut-turut tanpa alasan sah merupakan dasar hukuman berat berupa pemberhentian."],
      ["Pemotongan tunjangan 1%.", "Keliru. Ini bukan konsekuensi PP 94 untuk pelanggaran tersebut."],
      ["Tidak ada hukuman jika kemudian masuk kembali.", "Keliru. Kembali bekerja tidak menghapus pelanggaran yang sudah terjadi."],
    ],
    answer: 1,
    source: "pp94",
    reference: "Pelanggaran masuk kerja — 10 hari berturut-turut",
  },
  {
    id: 32,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Menjebak",
    stem: "Ketidakhadiran tanpa alasan sah secara kumulatif selama 28 hari kerja atau lebih dalam satu tahun berakibat…",
    options: [
      ["Teguran lisan.", "Keliru. Ambang ini termasuk pelanggaran berat."],
      ["Pernyataan tidak puas.", "Keliru. Itu hukuman ringan."],
      ["Pemberhentian dengan hormat tidak atas permintaan sendiri sebagai PNS.", "Benar. Ambang kumulatif 28 hari atau lebih berujung pada hukuman berat tersebut."],
      ["Hanya pembinaan informal.", "Keliru. Konsekuensinya telah ditentukan secara normatif."],
    ],
    answer: 2,
    source: "pp94",
    reference: "Pelanggaran masuk kerja — 28 hari kumulatif atau lebih",
  },
  {
    id: 33,
    topic: "Disiplin & Kepegawaian",
    difficulty: "Dasar",
    stem: "Pasangan regulasi dan pokok pengaturan yang tepat adalah…",
    options: [
      ["PP 79/2021 — Upaya Administratif dan BPASN.", "Benar. Regulasi ini menjadi dasar upaya administratif dalam sengketa kepegawaian ASN."],
      ["PMK 123/2023 — Standar Biaya Masukan.", "Keliru. PMK 123/2023 mengatur pemeriksaan pelanggaran disiplin di Kemenkeu."],
      ["UU 20/2023 — Penggunaan BMN.", "Keliru. UU 20/2023 mengatur ASN."],
      ["PP 11/2017 — Keterbukaan Informasi Publik.", "Keliru. PP 11/2017 mengatur Manajemen PNS."],
    ],
    answer: 0,
    source: "disiplin",
    reference: "Dasar hukum penegakan disiplin",
  },
  {
    id: 34,
    topic: "PPID",
    difficulty: "Dasar",
    stem: "Tiga kelompok Informasi Publik yang wajib dibuka menurut standar layanan adalah…",
    options: [
      ["Berkala, serta merta, dan tersedia setiap saat.", "Benar. Ini tiga kategori utama informasi yang wajib dibuka."],
      ["Rahasia negara, rahasia pribadi, dan rahasia jabatan.", "Keliru. Ini berkaitan dengan informasi yang tidak dapat diberikan/dikecualikan."],
      ["Internal, eksternal, dan diplomatik.", "Keliru. Bukan klasifikasi keterbukaan yang dimaksud."],
      ["Gratis, berbayar, dan bersubsidi.", "Keliru. Kategori tidak didasarkan pada biaya."],
    ],
    answer: 0,
    source: "perki",
    reference: "Pasal 13 — Informasi Publik yang wajib dibuka",
  },
  {
    id: 35,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Pengumuman Informasi Publik secara berkala dilakukan paling sedikit…",
    options: [
      ["Setiap minggu.", "Keliru. Tidak diwajibkan sesering itu untuk seluruh informasi berkala."],
      ["Satu tahun sekali.", "Keliru. Ini kurang sering daripada standar minimum."],
      ["Enam bulan sekali.", "Benar. PerKI 1/2021 menetapkan paling sedikit enam bulan sekali."],
      ["Hanya jika ada permintaan.", "Keliru. Informasi berkala wajib diumumkan secara proaktif."],
    ],
    answer: 2,
    source: "perki",
    reference: "Pasal 18 — frekuensi pengumuman berkala",
  },
  {
    id: 36,
    topic: "PPID",
    difficulty: "Analitik",
    stem: "Informasi mengenai bahaya yang dapat mengancam hajat hidup orang banyak dan ketertiban umum harus…",
    options: [
      ["Menunggu permohonan tertulis.", "Keliru. Sifat ancaman menuntut pengumuman proaktif."],
      ["Diumumkan secara serta merta dengan cara mudah dijangkau dan dipahami.", "Benar. Kecepatan, jangkauan, dan bahasa yang mudah dipahami menjadi prinsipnya."],
      ["Selalu dikecualikan.", "Keliru. Justru kategori ini wajib diumumkan segera."],
      ["Hanya dikirim kepada pegawai internal.", "Keliru. Sasaran utamanya masyarakat yang terdampak."],
    ],
    answer: 1,
    source: "uuKip",
    reference: "Pasal 10 — informasi serta merta",
  },
  {
    id: 37,
    topic: "PPID",
    difficulty: "Analitik",
    stem: "Manakah contoh yang paling tepat untuk informasi yang wajib tersedia setiap saat?",
    options: [
      ["Daftar Informasi Publik, keputusan beserta pertimbangan, dan kebijakan berikut dokumen pendukung.", "Benar. Ketiganya termasuk contoh eksplisit informasi tersedia setiap saat."],
      ["Data kesehatan pribadi seluruh pegawai.", "Keliru. Data kesehatan pribadi termasuk informasi yang dilindungi."],
      ["Kunci sandi sistem keamanan.", "Keliru. Informasi keamanan tertentu dapat dikecualikan."],
      ["Wasiat pribadi pejabat.", "Keliru. Isi akta/wasiat pribadi dilindungi."],
    ],
    answer: 0,
    source: "uuKip",
    reference: "Pasal 11 — informasi tersedia setiap saat",
  },
  {
    id: 38,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Batas waktu awal Badan Publik menyampaikan pemberitahuan tertulis atas permintaan informasi adalah…",
    options: [
      ["3 hari kalender.", "Keliru. Tiga hari kerja pada SE-15 terkait pelengkapan persyaratan, bukan jawaban awal."],
      ["7 hari kerja.", "Keliru. Tujuh hari adalah batas perpanjangan."],
      ["10 hari kerja sejak permintaan diterima.", "Benar. Ini batas waktu pemberitahuan tertulis awal."],
      ["30 hari kerja.", "Keliru. Tiga puluh hari terkait mekanisme keberatan."],
    ],
    answer: 2,
    source: "uuKip",
    reference: "Pasal 22 ayat (7)",
  },
  {
    id: 39,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Badan Publik memerlukan tambahan waktu untuk menentukan status informasi. Perpanjangan yang dibolehkan adalah…",
    options: [
      ["Paling lama 7 hari kerja berikutnya dengan alasan tertulis.", "Benar. Perpanjangan harus dibatasi dan disertai alasan."],
      ["30 hari kalender tanpa pemberitahuan.", "Keliru. Terlalu lama dan tanpa alasan tertulis."],
      ["Tidak terbatas selama informasi sulit dicari.", "Keliru. Keterbatasan waktu merupakan bagian standar layanan."],
      ["Hanya 1 hari kerja.", "Keliru. Undang-undang memberi ruang sampai tujuh hari kerja."],
    ],
    answer: 0,
    source: "uuKip",
    reference: "Pasal 22 ayat (8)",
  },
  {
    id: 40,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Pasangan jangka waktu keberatan yang tepat adalah…",
    options: [
      ["Pemohon 7 hari; Atasan PPID 10 hari.", "Keliru. Angka tersebut berkaitan dengan layanan permintaan awal."],
      ["Pemohon paling lambat 30 hari kerja sejak alasan ditemukan; Atasan PPID menjawab paling lambat 30 hari kerja.", "Benar. Kedua tahap menggunakan batas 30 hari kerja."],
      ["Pemohon 60 hari; Atasan PPID 90 hari.", "Keliru. Melebihi batas standar."],
      ["Tidak ada batas waktu.", "Keliru. Kepastian waktu adalah unsur penting layanan."],
    ],
    answer: 1,
    source: "uuKip",
    reference: "Pasal 36 — pengajuan dan tanggapan keberatan",
  },
  {
    id: 41,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Pemohon tidak puas atas keputusan Atasan PPID. Permohonan penyelesaian sengketa ke Komisi Informasi diajukan dalam jangka waktu…",
    options: [
      ["14 hari kerja sejak diterimanya tanggapan Atasan PPID atau berakhirnya batas tanggapan.", "Benar. Ini tahap setelah upaya keberatan internal."],
      ["3 hari kalender sejak permintaan pertama.", "Keliru. Terlalu awal; mekanisme keberatan harus dilalui."],
      ["30 tahun.", "Keliru. Jelas tidak sesuai standar penyelesaian sengketa."],
      ["Hanya setelah izin Badan Publik.", "Keliru. Hak mengajukan sengketa tidak bergantung pada izin badan yang disengketakan."],
    ],
    answer: 0,
    source: "perki",
    reference: "Maklumat prosedur layanan — pengajuan ke Komisi Informasi",
  },
  {
    id: 42,
    topic: "PPID",
    difficulty: "Dasar",
    stem: "PPID Pelaksana di lingkungan Kementerian Keuangan terdiri atas…",
    options: [
      ["PPID Tingkat I, II, dan III.", "Benar. Ketiganya membantu pelaksanaan tugas PPID Kementerian Keuangan secara berjenjang."],
      ["Hanya PPID Tingkat I.", "Keliru. Struktur mencakup tiga tingkatan."],
      ["PPK, PPSPM, dan Bendahara.", "Keliru. Itu jabatan pengelolaan keuangan, bukan PPID."],
      ["Juru Bicara I, II, dan III.", "Keliru. Juru bicara dan PPID memiliki fungsi berbeda."],
    ],
    answer: 0,
    source: "ppid",
    reference: "Ketentuan Umum — PPID Pelaksana",
  },
  {
    id: 43,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "PPID Tingkat I terutama bertanggung jawab pada…",
    options: [
      ["Unit eselon I/unit pimpinan tinggi madya dan unit non-eselon yang langsung bertanggung jawab kepada Menteri.", "Benar. Tingkat I berada pada level unit utama tersebut."],
      ["Setiap desa.", "Keliru. Bukan struktur PPID Kemenkeu."],
      ["Kantor pelayanan yang dipimpin pejabat administrator saja.", "Keliru. Ini lebih dekat dengan cakupan PPID Tingkat III."],
      ["Seluruh badan publik di Indonesia.", "Keliru. Lingkupnya Kementerian Keuangan."],
    ],
    answer: 0,
    source: "ppid",
    reference: "Ketentuan Umum — PPID Tingkat I",
  },
  {
    id: 44,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Cakupan yang paling sesuai untuk PPID Tingkat II adalah…",
    options: [
      ["Kantor wilayah dan kantor pelayanan yang dipimpin pejabat pimpinan tinggi pratama.", "Benar. Tingkat II melayani wilayah kerja pada level tersebut serta membantu PPID di atasnya."],
      ["Hanya Kantor Pusat Kementerian.", "Keliru. Kantor pusat/unit eselon I merupakan ranah Tingkat I."],
      ["Kantor pelayanan yang dipimpin pejabat administrator saja.", "Keliru. Ini cakupan Tingkat III."],
      ["Semua perusahaan swasta.", "Keliru. PPID Kemenkeu tidak menjadi PPID perusahaan swasta."],
    ],
    answer: 0,
    source: "ppid",
    reference: "Ketentuan Umum — PPID Tingkat II",
  },
  {
    id: 45,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "PPID Tingkat III berada pada wilayah kerja…",
    options: [
      ["Unit eselon I yang dipimpin pejabat pimpinan tinggi madya.", "Keliru. Ini Tingkat I."],
      ["Kantor wilayah yang dipimpin pejabat pimpinan tinggi pratama.", "Keliru. Ini masuk cakupan Tingkat II."],
      ["Kantor pelayanan dan/atau UPT yang dipimpin pejabat administrator.", "Benar. Tingkat III merupakan lapis layanan pada unit tersebut."],
      ["Komisi Informasi Pusat.", "Keliru. Komisi Informasi bukan bagian struktur PPID Pelaksana Kemenkeu."],
    ],
    answer: 2,
    source: "ppid",
    reference: "Ketentuan Umum — PPID Tingkat III",
  },
  {
    id: 46,
    topic: "PPID",
    difficulty: "Analitik",
    stem: "Pemohon penyandang disabilitas mengalami kesulitan mengisi formulir. Petugas seharusnya…",
    options: [
      ["Menolak permohonan karena formulir harus diisi sendiri.", "Keliru. Layanan wajib aksesibel."],
      ["Membantu pengisian formulir tanpa mengurangi hak dan verifikasi identitas pemohon.", "Benar. SE-15 secara eksplisit mengatur bantuan bagi pemohon penyandang disabilitas."],
      ["Meminta pemohon menunjuk pengacara.", "Keliru. Tidak ada kewajiban tersebut."],
      ["Mengubah permohonan menjadi pengaduan.", "Keliru. Jenis layanan tidak boleh diubah sepihak."],
    ],
    answer: 1,
    source: "se15",
    reference: "Layanan PPID DJBC — bantuan pengisian formulir",
  },
  {
    id: 47,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Permintaan Informasi Publik dinyatakan belum lengkap. Menurut SE-15/BC/2025, kekurangan harus dilengkapi dalam…",
    options: [
      ["3 hari kerja sejak surat ketidaklengkapan diterima.", "Benar. Jika tidak dilengkapi dalam jangka ini, permintaan diberitahukan tidak ditindaklanjuti."],
      ["10 hari kerja sejak permintaan awal.", "Keliru. Sepuluh hari adalah batas pemberitahuan tertulis PPID."],
      ["30 hari kerja.", "Keliru. Angka ini terkait keberatan."],
      ["Tanpa batas waktu.", "Keliru. Proses layanan membutuhkan kepastian."],
    ],
    answer: 0,
    source: "se15",
    reference: "Permintaan belum lengkap — batas pelengkapan",
  },
  {
    id: 48,
    topic: "PPID",
    difficulty: "Menjebak",
    stem: "Pasangan aplikasi dan fungsi yang tepat adalah…",
    options: [
      ["SPLIT untuk layanan/basis pengetahuan kepabeanan-cukai; SIPPID untuk pelayanan dan dokumentasi Informasi Publik.", "Benar. SPLIT mendukung layanan teknis kepabeanan-cukai, SIPPID mendukung proses PPID."],
      ["SPLIT untuk penggajian; SIPPID untuk pengadaan.", "Keliru. Keduanya bukan fungsi aplikasi tersebut."],
      ["SPLIT untuk hukuman disiplin; SIPPID untuk perjalanan dinas.", "Keliru. Penegakan disiplin dan perjalanan dinas menggunakan mekanisme lain."],
      ["Keduanya hanya untuk media sosial.", "Keliru. Fungsi keduanya lebih spesifik pada layanan informasi."],
    ],
    answer: 0,
    source: "se15",
    reference: "Definisi SPLIT dan Sistem Informasi PPID",
  },
  {
    id: 49,
    topic: "PPID",
    difficulty: "Analitik",
    stem: "Jika permintaan ditolak karena informasi dikecualikan, PPID wajib…",
    options: [
      ["Cukup menjawab 'rahasia' secara lisan.", "Keliru. Penolakan harus akuntabel dan tertulis."],
      ["Tidak perlu memberi dasar apa pun.", "Keliru. Pemohon berhak mengetahui dasar penolakan."],
      ["Menyampaikan pemberitahuan tertulis disertai keputusan klasifikasi dan/atau lembar Pengujian Konsekuensi.", "Benar. Dokumen tersebut menunjukkan dasar pengecualian."],
      ["Menghapus informasi dari arsip.", "Keliru. Pengecualian akses bukan perintah penghapusan arsip."],
    ],
    answer: 2,
    source: "ppid",
    reference: "Penolakan permintaan berdasarkan pengecualian",
  },
  {
    id: 50,
    topic: "PPID",
    difficulty: "Analitik",
    stem: "Manakah informasi yang paling jelas termasuk rahasia pribadi dan tidak otomatis dapat dibuka?",
    options: [
      ["Laporan keuangan badan publik yang wajib diumumkan.", "Keliru. Laporan keuangan badan publik termasuk informasi berkala."],
      ["Kondisi kesehatan, aset, pendapatan, dan rekening bank seseorang.", "Benar. Unsur tersebut secara eksplisit termasuk rahasia pribadi."],
      ["Daftar Informasi Publik.", "Keliru. DIP justru wajib tersedia setiap saat, tanpa memuat informasi dikecualikan."],
      ["Kebijakan badan publik berikut dokumen pendukung yang terbuka.", "Keliru. Ini termasuk informasi tersedia setiap saat sepanjang tidak ada bagian yang dikecualikan."],
    ],
    answer: 1,
    source: "uuKip",
    reference: "Pasal 17 huruf h — rahasia pribadi",
  },
  {
    id: 51,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Dasar",
    stem: "Ruang lingkup SE-15/BC/2025 mencakup…",
    options: [
      ["Pemberian Informasi melalui Media Massa dan Edukasi Publik serta Layanan Informasi.", "Benar. Ketiga ranah ini menjadi inti pedoman bagi fungsi kehumasan, penyuluhan, dan layanan informasi."],
      ["Hanya pengadaan alat komunikasi.", "Keliru. Pedoman mengatur proses komunikasi dan layanan, bukan semata barang."],
      ["Hanya komunikasi antarpegawai.", "Keliru. Komunikasi internal diatur khusus dalam SE-14/BC/2025."],
      ["Penindakan kepabeanan saja.", "Keliru. Penindakan bukan ruang lingkup utama SE-15."],
    ],
    answer: 0,
    source: "se15",
    reference: "Bagian C — Ruang Lingkup",
  },
  {
    id: 52,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Menjebak",
    stem: "Yang termasuk Media Massa dalam SE-15/BC/2025 adalah…",
    options: [
      ["Media cetak, elektronik, online, dan/atau media sosial.", "Benar. Definisinya menggunakan cakupan media tersebut."],
      ["Hanya surat kabar cetak.", "Keliru. Cakupannya jauh lebih luas."],
      ["Hanya televisi nasional.", "Keliru. Media elektronik hanya salah satu jenis."],
      ["Hanya akun pribadi pegawai.", "Keliru. Akun pribadi tidak otomatis menjadi kanal resmi/media yang berwenang."],
    ],
    answer: 0,
    source: "se15",
    reference: "Definisi Media Massa",
  },
  {
    id: 53,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Menjebak",
    stem: "Pasangan jenjang Juru Bicara DJBC yang tepat adalah…",
    options: [
      ["Tingkat I: KPPBC; Tingkat III: Unit Eselon I.", "Keliru. Susunannya terbalik."],
      ["Tingkat I: Pimpinan Unit Eselon I/pejabat yang ditunjuk; Tingkat II: pimpinan Kanwil/KPU atau pejabat yang ditunjuk; Tingkat III: pimpinan KPPBC/BLBC/PSO atau pejabat yang ditunjuk.", "Benar. Jenjangnya mengikuti level organisasi dan penunjukan pimpinan."],
      ["Semua pegawai otomatis Juru Bicara Tingkat I.", "Keliru. Kewenangan pernyataan media melekat pada pejabat yang ditentukan/ditunjuk."],
      ["Juru Bicara hanya ada di Kementerian, tidak di DJBC.", "Keliru. SE-15 mengatur tiga tingkat Juru Bicara DJBC."],
    ],
    answer: 1,
    source: "se15",
    reference: "Juru Bicara Tingkat I, II, dan III",
  },
  {
    id: 54,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Dasar",
    stem: "Siklus kegiatan komunikasi internal DJBC dalam SE-14/BC/2025 terdiri atas…",
    options: [
      ["Perencanaan, pelaksanaan, dan evaluasi.", "Benar. Ketiganya membentuk rangkaian pengelolaan komunikasi internal."],
      ["Pengadaan, lelang, dan pembayaran.", "Keliru. Ini siklus pengadaan/keuangan, bukan komunikasi internal."],
      ["Pemeriksaan, penyidikan, dan penuntutan.", "Keliru. Ini bukan ruang lingkup komunikasi internal."],
      ["Promosi, mutasi, dan pensiun.", "Keliru. Itu proses kepegawaian."],
    ],
    answer: 0,
    source: "se14",
    reference: "Bagian C — Ruang Lingkup",
  },
  {
    id: 55,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Analitik",
    stem: "Sebuah pesan kebijakan berbeda-beda antarunit sehingga pegawai bingung. Prinsip perbaikan yang paling sesuai SE-14 adalah…",
    options: [
      ["Membiarkan setiap unit menafsirkan tanpa koordinasi.", "Keliru. Ini memperbesar inkonsistensi."],
      ["Menjamin informasi konsisten, akurat, tepat sasaran, dan memperkuat pusat koordinasi.", "Benar. Tujuan pedoman adalah komunikasi terpadu yang mendukung keputusan dan pelaksanaan tugas."],
      ["Menghentikan seluruh komunikasi dua arah.", "Keliru. Pedoman justru mendorong komunikasi terbuka dan partisipatif."],
      ["Menyampaikan hanya melalui rumor informal.", "Keliru. Kanal dan koordinasi resmi diperlukan."],
    ],
    answer: 1,
    source: "se14",
    reference: "Bagian B — Tujuan Komunikasi Internal",
  },
  {
    id: 56,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Analitik",
    stem: "Program employee advocacy paling tepat dimaknai sebagai…",
    options: [
      ["Pegawai secara bertanggung jawab membantu menguatkan pesan dan reputasi organisasi sesuai pedoman.", "Benar. Advokasi pegawai memobilisasi pemahaman pegawai sebagai pendukung komunikasi institusi, tetap dalam koridor kewenangan."],
      ["Setiap pegawai bebas mengumumkan informasi dikecualikan.", "Keliru. Advokasi tidak menghapus klasifikasi informasi dan kewenangan juru bicara."],
      ["Pegawai wajib berdebat dengan semua kritik di media sosial.", "Keliru. Respons komunikasi harus terarah, proporsional, dan terkoordinasi."],
      ["Menggantikan seluruh fungsi juru bicara.", "Keliru. Employee advocacy melengkapi, bukan mengambil alih kewenangan resmi."],
    ],
    answer: 0,
    source: "komunikasi",
    reference: "Pedoman — program advokasi pegawai",
  },
  {
    id: 57,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Menjebak",
    stem: "Klasifikasi target komunikasi dalam Pedoman Pengelolaan Komunikasi Kemenkeu adalah…",
    options: [
      ["Internal primer, internal sekunder, eksternal primer, dan eksternal sekunder.", "Benar. Klasifikasi membedakan kedekatan dan karakter pemangku kepentingan."],
      ["Pusat, wilayah, kantor, dan desa.", "Keliru. Ini bukan klasifikasi target komunikasi dalam pedoman."],
      ["Pegawai tetap dan pegawai tidak tetap saja.", "Keliru. Target eksternal juga diatur."],
      ["Media cetak dan elektronik saja.", "Keliru. Itu klasifikasi saluran, bukan target."],
    ],
    answer: 0,
    source: "komunikasi",
    reference: "Target komunikasi",
  },
  {
    id: 58,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Analitik",
    stem: "Saat isu berstatus krisis, koordinasi komunikasi terutama ditujukan agar…",
    options: [
      ["Setiap unit membuat versi pesan yang berbeda.", "Keliru. Perbedaan pesan memperparah disinformasi."],
      ["Informasi satu suara, akurat, konsisten, cepat, transparan, dan berbasis data.", "Benar. Pola ini meminimalkan kepanikan dan menjaga kepercayaan publik."],
      ["Informasi ditunda tanpa batas.", "Keliru. Kecepatan merupakan unsur penanganan krisis."],
      ["Hanya rumor positif yang disebarkan.", "Keliru. Informasi harus dapat dipercaya dan berbasis data."],
    ],
    answer: 1,
    source: "komunikasi",
    reference: "Manajemen isu dan penanganan krisis",
  },
  {
    id: 59,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Menjebak",
    stem: "Petugas layanan informasi kepabeanan dan cukai dapat menggunakan sumber jawaban tervalidasi berikut, kecuali…",
    options: [
      ["Peraturan pada portal INSW.", "Keliru sebagai jawaban karena ini dapat menjadi sumber."],
      ["Basis pengetahuan bea dan cukai serta data tervalidasi pada SKP.", "Keliru sebagai jawaban karena keduanya termasuk sumber."],
      ["Standar pelayanan ICECSC.", "Keliru sebagai jawaban karena standar ini termasuk rujukan."],
      ["Pendapat pribadi yang belum diverifikasi.", "Benar sebagai pilihan 'kecuali'. Layanan harus berbasis informasi yang sah dan tervalidasi."],
    ],
    answer: 3,
    source: "se15",
    reference: "Sumber informasi layanan kepabeanan dan cukai",
  },
  {
    id: 60,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Dasar",
    stem: "Pada unit vertikal DJBC, SPLIT digunakan terutama untuk…",
    options: [
      ["Merekam permohonan informasi kepabeanan-cukai dan memvalidasi jawabannya oleh pejabat yang menangani layanan.", "Benar. Ini dua fungsi pokok pada unit vertikal."],
      ["Menetapkan hukuman disiplin.", "Keliru. Penegakan disiplin menggunakan mekanisme/aplikasi tersendiri."],
      ["Menghitung gaji pegawai.", "Keliru. SPLIT bukan aplikasi penggajian."],
      ["Menggantikan seluruh proses SIPPID.", "Keliru. SPLIT dan SIPPID memiliki ranah layanan berbeda."],
    ],
    answer: 0,
    source: "se15",
    reference: "Pengelolaan Layanan Informasi melalui SPLIT",
  },
  {
    id: 61,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Dasar",
    stem: "Contoh Edukasi Publik menurut SE-15/BC/2025 adalah…",
    options: [
      ["Acara, pameran, atau kegiatan sejenis terkait keuangan negara serta tugas dan fungsi DJBC.", "Benar. Edukasi Publik menjangkau masyarakat melalui format edukatif tersebut."],
      ["Pemeriksaan rahasia pegawai.", "Keliru. Itu bukan kegiatan edukasi publik."],
      ["Sidang TPK.", "Keliru. Sidang TPK adalah tata kelola kinerja internal."],
      ["Rapat tertutup penanganan perkara.", "Keliru. Kegiatan ini bukan edukasi kepada masyarakat."],
    ],
    answer: 0,
    source: "se15",
    reference: "Definisi Edukasi Publik",
  },
  {
    id: 62,
    topic: "Komunikasi & Penyuluhan",
    difficulty: "Analitik",
    stem: "Seorang pelaksana diminta wartawan memberi pernyataan kebijakan yang sensitif. Tindakan terbaik adalah…",
    options: [
      ["Menjawab berdasarkan dugaan pribadi agar cepat.", "Keliru. Kecepatan tanpa kewenangan dan validasi berisiko menimbulkan disinformasi."],
      ["Mengarahkan kepada Juru Bicara yang berwenang dan meneruskan permintaan melalui kanal koordinasi.", "Benar. Pernyataan melalui media massa merupakan kewenangan Juru Bicara."],
      ["Menghapus pertanyaan wartawan.", "Keliru. Permintaan seharusnya dikelola, bukan dihilangkan."],
      ["Mengunggah dokumen internal apa pun sebagai bukti.", "Keliru. Klasifikasi dan kewenangan informasi tetap harus dijaga."],
    ],
    answer: 1,
    source: "se15",
    reference: "Pemberian Informasi melalui Media Massa",
  },
  {
    id: 63,
    topic: "Kepatuhan Internal",
    difficulty: "Dasar",
    stem: "Kepatuhan Internal dalam materi UKI DJBC mencakup kesesuaian…",
    options: [
      ["Pelaksanaan tugas unit dan perilaku/ucapan/tindakan pegawai terhadap ketentuan.", "Benar. Definisinya mencakup dimensi proses kerja dan dimensi perilaku pegawai."],
      ["Hanya realisasi anggaran.", "Keliru. Cakupannya lebih luas dari keuangan."],
      ["Hanya kehadiran fisik.", "Keliru. Kehadiran hanya salah satu potensi aspek disiplin."],
      ["Hanya hasil survei eksternal.", "Keliru. UKI menangani kepatuhan internal secara komprehensif."],
    ],
    answer: 0,
    source: "uki",
    reference: "Definisi Kepatuhan Internal",
  },
  {
    id: 64,
    topic: "Kepatuhan Internal",
    difficulty: "Analitik",
    stem: "Peran UKI yang paling tepat adalah…",
    options: [
      ["Menggantikan seluruh tanggung jawab pimpinan unit.", "Keliru. Pimpinan tetap pemilik tanggung jawab pengendalian."],
      ["Mendukung pimpinan unit dalam pengendalian pelaksanaan tugas dan penegakan ketentuan perilaku pegawai.", "Benar. UKI berperan sebagai pendukung pimpinan, bukan pengganti manajemen."],
      ["Bertindak sebagai pengadilan pidana.", "Keliru. UKI bukan lembaga peradilan."],
      ["Hanya menyusun publikasi media.", "Keliru. Itu fungsi komunikasi, bukan peran inti UKI."],
    ],
    answer: 1,
    source: "uki",
    reference: "Peran UKI",
  },
  {
    id: 65,
    topic: "Kepatuhan Internal",
    difficulty: "Menjebak",
    stem: "Empat fungsi Kepatuhan Internal yang disebut dalam materi adalah…",
    options: [
      ["Pencegahan, Pengawasan, Penjaminan Kualitas, dan Pengelolaan Kinerja.", "Benar. Keempatnya membentuk portofolio fungsi UKI."],
      ["Perencanaan, pengadaan, pembayaran, dan pelaporan.", "Keliru. Ini bukan pembagian fungsi KI."],
      ["Intelijen, penindakan, penyidikan, dan penuntutan.", "Keliru. Tidak sesuai klasifikasi fungsi UKI."],
      ["Rekrutmen, mutasi, promosi, dan pensiun.", "Keliru. Ini ranah manajemen SDM."],
    ],
    answer: 0,
    source: "uki",
    reference: "Fungsi Kepatuhan Internal",
  },
  {
    id: 66,
    topic: "Kepatuhan Internal",
    difficulty: "Menjebak",
    stem: "Manakah yang merupakan contoh fungsi Pencegahan UKI?",
    options: [
      ["Pengendalian gratifikasi dan pemantauan pelaporan harta kekayaan/perpajakan pegawai.", "Benar. Keduanya ditujukan mencegah risiko integritas sebelum berkembang menjadi pelanggaran."],
      ["Penetapan putusan pengadilan.", "Keliru. UKI tidak menetapkan putusan pengadilan."],
      ["Penyusunan APBN.", "Keliru. Ini bukan fungsi pencegahan UKI."],
      ["Penetapan tarif bea masuk nasional.", "Keliru. Itu kebijakan kepabeanan, bukan fungsi UKI unit."],
    ],
    answer: 0,
    source: "uki",
    reference: "Fungsi Pencegahan",
  },
  {
    id: 67,
    topic: "Kepatuhan Internal",
    difficulty: "Analitik",
    stem: "PKPT, investigasi internal, pemeriksaan mendadak, dan surveillance dikelompokkan ke fungsi…",
    options: [
      ["Pencegahan.", "Keliru. Pencegahan berfokus edukasi dan kontrol preventif."],
      ["Pengawasan.", "Benar. Kegiatan tersebut merupakan alat pengawasan UKI."],
      ["Pengelolaan Kinerja.", "Keliru. Pengelolaan kinerja menangani PK, NKO, dan pelaporan kinerja."],
      ["Kehumasan.", "Keliru. Kegiatan tersebut bukan komunikasi publik."],
    ],
    answer: 1,
    source: "uki",
    reference: "Fungsi Pengawasan",
  },
  {
    id: 68,
    topic: "Kepatuhan Internal",
    difficulty: "Analitik",
    stem: "Evaluasi Risk and Control Matrix (RCM) dan pemantauan penerapan SPI termasuk fungsi…",
    options: [
      ["Penjaminan Kualitas.", "Benar. UKI menilai kecukupan rancangan/penerapan pengendalian dan mengusulkan perbaikannya."],
      ["Penyuluhan eksternal.", "Keliru. RCM/SPI adalah tata kelola internal."],
      ["Pengadaan.", "Keliru. Bukan proses pemilihan penyedia."],
      ["Protokoler.", "Keliru. Tidak berkaitan dengan keprotokolan."],
    ],
    answer: 0,
    source: "uki",
    reference: "Fungsi Penjaminan Kualitas — SPI dan RCM",
  },
  {
    id: 69,
    topic: "Kepatuhan Internal",
    difficulty: "Analitik",
    stem: "Dalam reviu manajemen risiko, UKI paling tepat melakukan…",
    options: [
      ["Reviu kepatuhan penyusunan profil/mitigasi risiko, pelaksanaan mitigasi, serta tindak lanjut reviu/audit.", "Benar. Rangkaian ini memastikan risiko tidak hanya didokumentasikan tetapi juga dimitigasi."],
      ["Menghapus semua risiko dari profil.", "Keliru. Risiko dikelola, bukan disangkal."],
      ["Menyerahkan seluruh risiko kepada auditor eksternal.", "Keliru. Manajemen dan UKI tetap memiliki peran internal."],
      ["Hanya menilai warna dokumen.", "Keliru. Reviu bersifat substantif."],
    ],
    answer: 0,
    source: "uki",
    reference: "Fungsi Penjaminan Kualitas — reviu manajemen risiko",
  },
  {
    id: 70,
    topic: "Kepatuhan Internal",
    difficulty: "Menjebak",
    stem: "Dalam materi UKI, tiga output penilaian kinerja organisasi adalah…",
    options: [
      ["NKO, NKO berdasarkan K3, dan Predikat Kinerja Organisasi.", "Benar. Ketiganya disebut sebagai keluaran penilaian kinerja organisasi."],
      ["SKP, daftar hadir, dan rekening koran.", "Keliru. Bukan tiga output penilaian organisasi."],
      ["Nilai ujian, ijazah, dan sertifikat.", "Keliru. Ini bukan konteks manajemen kinerja organisasi."],
      ["DIPA, kontrak, dan kuitansi.", "Keliru. Ketiganya dokumen keuangan/pengadaan."],
    ],
    answer: 0,
    source: "uki",
    reference: "Fungsi Pengelolaan Kinerja",
  },
  {
    id: 71,
    topic: "Kepatuhan Internal",
    difficulty: "Menjebak",
    stem: "Pasangan kedudukan UKI dan unitnya yang tepat adalah…",
    options: [
      ["Kantor Pusat: Direktorat KI; Kanwil/KPU: Bidang KI/KILI; KPPBC: Seksi KI/KIP; PSO/BLBC: Subbagian Umum dan KI.", "Benar. Bentuk unit KI menyesuaikan struktur tiap level organisasi."],
      ["Semua level: Direktorat KI.", "Keliru. Direktorat hanya pada Kantor Pusat."],
      ["KPPBC: Biro KI.", "Keliru. Pada KPPBC berbentuk Seksi KI/KIP."],
      ["PSO/BLBC tidak memiliki fungsi KI.", "Keliru. Fungsi KI melekat pada Subbagian Umum dan KI."],
    ],
    answer: 0,
    source: "uki",
    reference: "Kedudukan UKI",
  },
  {
    id: 72,
    topic: "Kepatuhan Internal",
    difficulty: "Analitik",
    stem: "Wilayah kerja UKI Kanwil BC mencakup…",
    options: [
      ["Hanya pegawai pada gedung Kanwil.", "Keliru. Cakupannya meluas ke unit vertikal di wilayahnya."],
      ["Pegawai dan unit Kanwil serta KPPBC, PSO BC, dan BLBC di wilayah kerjanya.", "Benar. Ini mencerminkan fungsi pembinaan/pengawasan berjenjang."],
      ["Seluruh kementerian di Indonesia.", "Keliru. Cakupan organisasi tetap DJBC di wilayahnya."],
      ["Hanya pengguna jasa.", "Keliru. UKI berfokus pada pegawai dan unit kerja internal."],
    ],
    answer: 1,
    source: "uki",
    reference: "Wilayah Kerja UKI",
  },
  {
    id: 73,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Dasar",
    stem: "Hari lahir Bea Cukai Indonesia dipandang jatuh pada…",
    options: [
      ["1 Oktober 1946, saat Pejabatan Bea dan Cukai dibentuk.", "Benar. Tanggal dan nama lembaga ini menjadi tonggak pascakemerdekaan."],
      ["17 Agustus 1945, saat nama DJBC langsung digunakan.", "Keliru. Nama DJBC belum digunakan saat itu."],
      ["30 Oktober 1948, saat VOC berdiri.", "Keliru. VOC jauh lebih awal; 30 Oktober terkait Hari Oeang."],
      ["1 April 1997, saat Pejabatan pertama dibentuk.", "Keliru. Tanggal itu terkait efektivitas UU Kepabeanan, bukan kelahiran institusi."],
    ],
    answer: 0,
    source: "organisasi",
    reference: "Sejarah Bea Cukai — masa kemerdekaan",
  },
  {
    id: 74,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Kepala Pejabatan Bea dan Cukai yang pertama adalah…",
    options: [
      ["Sjafrudin Prawiranegara.", "Keliru. Beliau Menteri Muda Keuangan yang menunjuk kepala pertama."],
      ["R.A. Kartadjoemena.", "Benar. Ia ditunjuk sebagai Kepala Pejabatan Bea dan Cukai pertama."],
      ["Daendels.", "Keliru. Bukan kepala pertama lembaga pascakemerdekaan tersebut."],
      ["Wahono Hadi.", "Keliru. Nama ini terkait pencipta Mars Bea dan Cukai."],
    ],
    answer: 1,
    source: "organisasi",
    reference: "Sejarah Bea Cukai — kepala pertama",
  },
  {
    id: 75,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Urutan perubahan nama lembaga setelah kemerdekaan yang tepat adalah…",
    options: [
      ["DJBC → Pejabatan → Jawatan.", "Keliru. Urutannya terbalik."],
      ["Pejabatan Bea dan Cukai (1946) → Jawatan Bea dan Cukai (1948) → DJBC (sejak 1965).", "Benar. Perubahan 1948 didasarkan PP 51/1948."],
      ["Jawatan → VOC → DJBC.", "Keliru. VOC adalah periode kolonial yang lebih awal."],
      ["Pejabatan → Kementerian Perdagangan → DJBC.", "Keliru. Urutan ini tidak sesuai materi sejarah."],
    ],
    answer: 1,
    source: "organisasi",
    reference: "Sejarah Bea Cukai — perubahan nama",
  },
  {
    id: 76,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Pada masa pendudukan Jepang, tugas Bea Cukai sementara berfokus pada…",
    options: [
      ["Bea impor dan ekspor saja.", "Keliru. Justru pengurusan bea impor/ekspor ditiadakan."],
      ["Cukai saja.", "Benar. Berdasarkan ketentuan saat itu, tugas impor dan ekspor ditiadakan sementara."],
      ["Pajak penghasilan.", "Keliru. Bukan fokus lembaga Bea Cukai."],
      ["Pengelolaan moneter.", "Keliru. Bukan tugas kepabeanan/cukai."],
    ],
    answer: 1,
    source: "organisasi",
    reference: "Sejarah Bea Cukai — masa pendudukan Jepang",
  },
  {
    id: 77,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Nama resmi lembaga pada masa Hindia Belanda, De Dienst der Invoer en Uitvoerrechten en Accijnzen, secara bebas berarti…",
    options: [
      ["Dinas Bea Impor dan Bea Ekspor serta Cukai.", "Benar. Invoerrechten, uitvoerrechten, dan accijnzen merujuk pada bea impor, ekspor, dan cukai."],
      ["Dinas Pajak Penghasilan dan Pertambahan Nilai.", "Keliru. Bukan terjemahan istilah tersebut."],
      ["Dinas Perdagangan Dalam Negeri saja.", "Keliru. Nama tersebut jelas memuat fungsi impor/ekspor/cukai."],
      ["Dinas Angkatan Laut Kerajaan.", "Keliru. Bukan lembaga militer."],
    ],
    answer: 0,
    source: "organisasi",
    reference: "Sejarah Bea Cukai — masa Hindia Belanda",
  },
  {
    id: 78,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Asal istilah 'bea' dan 'cukai' menurut materi sejarah adalah…",
    options: [
      ["Bea dari Sanskerta; cukai dari bahasa India.", "Benar. Asal istilah ini dijelaskan dalam sejarah DJBC."],
      ["Bea dari Belanda; cukai dari Jepang.", "Keliru. Tidak sesuai materi."],
      ["Keduanya dari Latin.", "Keliru. Bukan asal yang disebut."],
      ["Keduanya singkatan modern.", "Keliru. Keduanya merupakan istilah historis."],
    ],
    answer: 0,
    source: "organisasi",
    reference: "Sejarah Bea Cukai — asal istilah",
  },
  {
    id: 79,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Tongkat dengan delapan ulir pada logo DJBC melambangkan…",
    options: [
      ["Delapan nilai dasar ASN.", "Keliru. Nilai dasar ASN bukan makna unsur ini."],
      ["Hubungan perdagangan internasional Indonesia dengan mancanegara dari delapan penjuru mata angin.", "Benar. Jumlah ulir dan penjuru mata angin saling terkait."],
      ["Delapan kantor wilayah pertama.", "Keliru. Bukan makna resmi logo."],
      ["Delapan jenis cukai.", "Keliru. Jumlah jenis BKC bukan filosofi unsur logo ini."],
    ],
    answer: 1,
    source: "organisasi",
    reference: "Logo Bea Cukai — makna tongkat",
  },
  {
    id: 80,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Tiga puluh sayap kecil dan sepuluh sayap besar pada logo terutama mengingatkan pada…",
    options: [
      ["Hari Oeang Republik Indonesia, 30 Oktober, serta kedudukan DJBC sebagai unsur pelaksana Kemenkeu.", "Benar. Angka 30 dan 10 membentuk tanggal 30 Oktober."],
      ["Hari Kemerdekaan 17 Agustus.", "Keliru. Bukan angka yang direpresentasikan sayap."],
      ["Hari lahir Bea Cukai 1 Oktober.", "Keliru. Walau bulan sama, unsur sayap merujuk 30 Oktober."],
      ["Jumlah provinsi.", "Keliru. Bukan makna resmi."],
    ],
    answer: 0,
    source: "organisasi",
    reference: "Logo Bea Cukai — makna sayap",
  },
  {
    id: 81,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Lingkaran malai padi dengan 24 butir pada logo melambangkan…",
    options: [
      ["Jumlah jam dalam sehari saja.", "Keliru. Makna resminya tidak dirumuskan sebagai jam."],
      ["Tujuan pelaksanaan tugas DJBC: kemakmuran dan kesejahteraan Indonesia.", "Benar. Malai padi merupakan simbol tujuan kesejahteraan."],
      ["Jumlah kantor pelayanan.", "Keliru. Tidak terkait jumlah unit."],
      ["Batas tarif bea masuk.", "Keliru. Bukan simbol tarif."],
    ],
    answer: 1,
    source: "organisasi",
    reference: "Logo Bea Cukai — makna malai padi",
  },
  {
    id: 82,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Menjebak",
    stem: "Pasangan warna logo dan makna yang tepat adalah…",
    options: [
      ["Kuning—penjaga keuangan negara; putih—kesucian pengabdian; hitam—keteguhan menjaga wilayah RI.", "Benar. Ketiga warna memiliki makna yang saling melengkapi."],
      ["Kuning—rahasia; putih—hukuman; hitam—kemewahan.", "Keliru. Tidak sesuai filosofi resmi."],
      ["Semua warna hanya dekorasi.", "Keliru. Materi menjelaskan makna masing-masing warna."],
      ["Putih—perdagangan internasional; hitam—Hari Oeang.", "Keliru. Makna tersebut melekat pada unsur lain."],
    ],
    answer: 0,
    source: "organisasi",
    reference: "Logo Bea Cukai — warna dan makna",
  },
  {
    id: 83,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Dasar",
    stem: "Lima Sikap Dasar Pegawai DJBC adalah…",
    options: [
      ["Jujur, Korsa, Loyal, Inisiatif, Korektif.", "Benar. Kelimanya menjadi fondasi perilaku pegawai DJBC."],
      ["Cepat, Keras, Rahasia, Mahal, Formal.", "Keliru. Bukan Sikap Dasar DJBC."],
      ["Integritas, Profesionalisme, Sinergi, Pelayanan, Kesempurnaan.", "Keliru. Ini dikenal sebagai Nilai-Nilai Kementerian Keuangan, bukan lima Sikap Dasar DJBC."],
      ["Berani, Kaya, Populer, Bebas, Individual.", "Keliru. Bertentangan dengan semangat organisasi."],
    ],
    answer: 0,
    source: "organisasi",
    reference: "Sikap Dasar Bea Cukai",
  },
  {
    id: 84,
    topic: "Organisasi, Sejarah & Logo",
    difficulty: "Analitik",
    stem: "DJBC memberi fasilitas untuk memperlancar perdagangan sekaligus asistensi kepada industri dalam negeri. Peran yang paling terkait adalah…",
    options: [
      ["Trade Facilitator dan Industrial Assistance.", "Benar. Fasilitasi arus perdagangan dan dukungan industri merupakan dua peran tersebut."],
      ["Revenue Collector saja.", "Keliru. Revenue Collector berfokus penerimaan."],
      ["Community Protector saja.", "Keliru. Community Protector berfokus perlindungan masyarakat."],
      ["PPID dan UKI.", "Keliru. Keduanya fungsi tata kelola, bukan empat peran utama customs."],
    ],
    answer: 0,
    source: "organisasi",
    reference: "Sekilas Bea Cukai — peran customs modern",
  },
  {
    id: 85,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Dasar",
    stem: "Tata Naskah Dinas (TND) mencakup pengelolaan…",
    options: [
      ["Jenis, format, penyiapan, pengamanan, pengabsahan, pendistribusian, penyimpanan, dan media komunikasi kedinasan.", "Benar. Definisi TND mencakup seluruh siklus naskah tersebut."],
      ["Hanya pengetikan surat.", "Keliru. TND jauh lebih luas."],
      ["Hanya pemusnahan arsip.", "Keliru. Penyimpanan merupakan satu aspek, bukan keseluruhan."],
      ["Hanya tanda tangan basah.", "Keliru. TND juga mengakomodasi proses elektronik."],
    ],
    answer: 0,
    source: "tnd",
    reference: "Definisi Tata Naskah Dinas",
  },
  {
    id: 86,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Menjebak",
    stem: "Susunan dasar Naskah Dinas adalah…",
    options: [
      ["Kepala, batang tubuh, dan kaki.", "Benar. Ini tiga bagian struktural utama."],
      ["Sampul, kuitansi, dan kontrak.", "Keliru. Bukan susunan universal Naskah Dinas."],
      ["Judul dan tanda tangan saja.", "Keliru. Tidak lengkap."],
      ["Lampiran saja.", "Keliru. Lampiran bersifat sesuai kebutuhan, bukan seluruh susunan."],
    ],
    answer: 0,
    source: "tnd",
    reference: "Susunan Naskah Dinas",
  },
  {
    id: 87,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Menjebak",
    stem: "Pasangan jenis Naskah Dinas dan contoh yang tepat adalah…",
    options: [
      ["Arahan—peraturan/instruksi/SE/SOP; Korespondensi intern—nota dinas; Khusus—berita acara/notula.", "Benar. Contoh tersebut sesuai kelompok masing-masing."],
      ["Arahan—kuitansi; Korespondensi—DIPA; Khusus—SKP.", "Keliru. Contohnya bukan klasifikasi TND yang dimaksud."],
      ["Korespondensi intern—surat dinas ekstern.", "Keliru. Korespondensi intern menggunakan nota dinas."],
      ["Khusus—peraturan menteri.", "Keliru. Peraturan termasuk Naskah Dinas arahan/pengaturan."],
    ],
    answer: 0,
    source: "tnd",
    reference: "Jenis dan Format Naskah Dinas",
  },
  {
    id: 88,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Menjebak",
    stem: "Penggunaan identitas pada kepala Naskah Dinas yang tepat adalah…",
    options: [
      ["Jabatan Menteri Keuangan menggunakan Lambang Negara; unit organisasi menggunakan Logo Kementerian Keuangan.", "Benar. Pembedaan ini mengikuti kedudukan penandatangan/unit."],
      ["Semua naskah menggunakan logo pribadi pejabat.", "Keliru. Identitas harus resmi dan dibakukan."],
      ["Unit organisasi selalu menggunakan Lambang Negara.", "Keliru. Lambang Negara digunakan pada kepala naskah jabatan Menteri."],
      ["Tidak boleh menggunakan identitas apa pun.", "Keliru. Kepala naskah justru memuat identitas resmi."],
    ],
    answer: 0,
    source: "tnd",
    reference: "Kepala Naskah Dinas",
  },
  {
    id: 89,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Analitik",
    stem: "Aplikasi Nadine mengalami gangguan sehingga naskah mendesak harus diproses. Tindakan yang sesuai pedoman adalah…",
    options: [
      ["Menghentikan semua layanan tanpa alternatif.", "Keliru. Pedoman menyediakan mekanisme kontinjensi."],
      ["Memproses secara manual dengan media rekam kertas serta pencatatan dan pendokumentasian yang dipersyaratkan.", "Benar. Prosedur manual berlaku ketika aplikasi tidak dapat diakses."],
      ["Menggunakan akun media sosial pribadi.", "Keliru. Bukan kanal persuratan resmi."],
      ["Meniadakan pengabsahan.", "Keliru. Gangguan aplikasi tidak menghapus kebutuhan pengabsahan."],
    ],
    answer: 1,
    source: "tnd",
    reference: "Penanganan saat aplikasi elektronik mengalami gangguan",
  },
  {
    id: 90,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Dasar",
    stem: "Barang Milik Negara adalah…",
    options: [
      ["Semua barang yang dibeli/diperoleh atas beban APBN atau berasal dari perolehan lain yang sah.", "Benar. Sumber perolehan APBN maupun sumber sah lain termasuk definisinya."],
      ["Hanya tanah milik pemerintah.", "Keliru. BMN mencakup berbagai jenis barang."],
      ["Semua barang pribadi pegawai di kantor.", "Keliru. Kepemilikan pribadi tidak berubah menjadi BMN hanya karena lokasi."],
      ["Barang yang dibeli dari APBD untuk pemerintah daerah.", "Keliru. Itu masuk ranah Barang Milik Daerah."],
    ],
    answer: 0,
    source: "bmn40",
    reference: "Pasal 1 — definisi BMN",
  },
  {
    id: 91,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Menjebak",
    stem: "PMK 40 Tahun 2024 secara khusus mengatur…",
    options: [
      ["Tata Cara Penggunaan BMN dan menggantikan ketentuan lama PMK 246/PMK.06/2014 beserta perubahannya.", "Benar. PMK ini menyesuaikan penggunaan BMN dengan PP 28/2020."],
      ["Standar Biaya Masukan 2026.", "Keliru. Itu PMK 32/2025."],
      ["Perjalanan Dinas Dalam Negeri.", "Keliru. Itu PMK 113/2012 jo. PMK 119/2023."],
      ["Tata Naskah Dinas.", "Keliru. Itu PMK 164/2021."],
    ],
    answer: 0,
    source: "bmn40",
    reference: "Judul dan riwayat penggantian regulasi",
  },
  {
    id: 92,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Analitik",
    stem: "BMN tidak lagi digunakan untuk menyelenggarakan tugas dan fungsi kementerian/lembaga. Rujukan khusus terbaru yang relevan adalah…",
    options: [
      ["PMK 120 Tahun 2024.", "Benar. PMK ini mengatur tata cara pengelolaan BMN yang tidak digunakan/tidak lagi digunakan untuk tusi."],
      ["PMK 110 Tahun 2022.", "Keliru. Ini pedoman layanan Informasi Publik."],
      ["KMK 127 Tahun 2026.", "Keliru. Ini manajemen kinerja."],
      ["UU 14 Tahun 2008.", "Keliru. Ini keterbukaan informasi publik."],
    ],
    answer: 0,
    source: "bmn120",
    reference: "Judul dan ruang lingkup",
  },
  {
    id: 93,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Menjebak",
    stem: "Perbedaan Standar Barang dan Standar Kebutuhan BMN yang tepat adalah…",
    options: [
      ["Standar Barang adalah spesifikasi; Standar Kebutuhan adalah jumlah yang dibutuhkan.", "Benar. Keduanya menjadi acuan perencanaan kebutuhan, pengadaan, dan penggunaan."],
      ["Standar Barang adalah jumlah; Standar Kebutuhan adalah warna.", "Keliru. Definisinya terbalik dan tidak lengkap."],
      ["Keduanya hanya menentukan harga jual.", "Keliru. Fokusnya spesifikasi dan jumlah kebutuhan."],
      ["Keduanya tidak terkait perencanaan.", "Keliru. Justru menjadi pedoman perencanaan kebutuhan BMN."],
    ],
    answer: 0,
    source: "bmn138",
    reference: "Definisi Standar Barang dan Standar Kebutuhan",
  },
  {
    id: 94,
    topic: "Umum, Rumah Tangga & BMN",
    difficulty: "Menjebak",
    stem: "Untuk struktur organisasi pusat Kementerian Keuangan yang mutakhir per Juli 2026, rujukan yang tepat adalah…",
    options: [
      ["PMK 124 Tahun 2024 sebagaimana diubah dengan PMK 117 Tahun 2025.", "Benar. PMK 124/2024 mencabut OTK lama dan telah diubah PMK 117/2025."],
      ["PMK 118/PMK.01/2021 tanpa melihat pencabutannya.", "Keliru. PMK 118/2021 telah dicabut oleh PMK 124/2024."],
      ["PP 61 Tahun 2010.", "Keliru. PP ini melaksanakan UU KIP."],
      ["PerKI 1 Tahun 2021.", "Keliru. Ini standar layanan informasi publik."],
    ],
    answer: 0,
    source: "otk",
    reference: "Riwayat dokumen OTK Kementerian Keuangan",
  },
  {
    id: 95,
    topic: "Keuangan & Pengadaan",
    difficulty: "Menjebak",
    stem: "Rujukan terbaru untuk perencanaan anggaran, pelaksanaan anggaran, serta akuntansi dan pelaporan keuangan adalah…",
    options: [
      ["PMK 62 Tahun 2023 sebagaimana diubah terakhir dengan PMK 41 Tahun 2026.", "Benar. PMK 41/2026 merupakan perubahan kedua dan berlaku sejak 22 Juni 2026."],
      ["PMK 107 Tahun 2024 saja tanpa perubahan 2026.", "Keliru. PMK 107/2024 telah diubah lagi oleh PMK 41/2026."],
      ["PMK 32 Tahun 2025 saja.", "Keliru. PMK 32/2025 mengatur SBM TA 2026."],
      ["Perpres 46 Tahun 2025 saja.", "Keliru. Perpres ini mengatur PBJ, bukan keseluruhan siklus anggaran dan akuntansi."],
    ],
    answer: 0,
    source: "anggaran",
    reference: "Riwayat perubahan PMK 62/2023",
  },
  {
    id: 96,
    topic: "Keuangan & Pengadaan",
    difficulty: "Menjebak",
    stem: "Standar Biaya Masukan untuk Tahun Anggaran 2026 ditetapkan melalui…",
    options: [
      ["PMK 32 Tahun 2025.", "Benar. Tahun regulasi 2025 menetapkan SBM untuk tahun anggaran berikutnya, 2026."],
      ["PMK 39 Tahun 2024.", "Keliru. PMK ini menetapkan SBM TA 2025."],
      ["PMK 79 Tahun 2025.", "Keliru. Ini Standar Struktur Biaya."],
      ["KMK 127 Tahun 2026.", "Keliru. Ini manajemen kinerja."],
    ],
    answer: 0,
    source: "sbm",
    reference: "Judul dan tahun anggaran",
  },
  {
    id: 97,
    topic: "Keuangan & Pengadaan",
    difficulty: "Menjebak",
    stem: "PMK 79 Tahun 2025 tentang Standar Struktur Biaya…",
    options: [
      ["Mencabut PMK 195/PMK.02/2014 dan PMK 140/PMK.02/2021.", "Benar. Kedua regulasi lama dinyatakan dicabut."],
      ["Menggantikan UU 17 Tahun 2003.", "Keliru. PMK tidak menggantikan undang-undang."],
      ["Mengatur logo DJBC.", "Keliru. Logo DJBC diatur dengan keputusan tersendiri."],
      ["Mengatur PPID Tingkat III.", "Keliru. Ini bukan regulasi keterbukaan informasi."],
    ],
    answer: 0,
    source: "ssb",
    reference: "Riwayat dokumen",
  },
  {
    id: 98,
    topic: "Keuangan & Pengadaan",
    difficulty: "Analitik",
    stem: "Regulasi perjalanan dinas dalam negeri yang masih menjadi rujukan setelah pembaruan adalah…",
    options: [
      ["PMK 113/PMK.05/2012 sebagaimana diubah dengan PMK 119 Tahun 2023, termasuk penguatan Sistem Elektronik Perjalanan Dinas.", "Benar. PMK 119/2023 mengubah ketentuan 2012 dan memperkuat proses elektronik."],
      ["PMK 113/2012 tanpa memperhatikan perubahan apa pun.", "Keliru. Perubahan 2023 harus dibaca bersama aturan induk."],
      ["PMK 164/2021.", "Keliru. Ini tata naskah dinas."],
      ["PP 94/2021.", "Keliru. Ini disiplin PNS."],
    ],
    answer: 0,
    source: "perdin",
    reference: "Riwayat dokumen dan pokok perubahan",
  },
  {
    id: 99,
    topic: "Keuangan & Pengadaan",
    difficulty: "Menjebak",
    stem: "Perpres 46 Tahun 2025 berkedudukan sebagai…",
    options: [
      ["Perubahan kedua atas Perpres 16 Tahun 2018 tentang Pengadaan Barang/Jasa Pemerintah.", "Benar. Perubahan pertama adalah Perpres 12/2021."],
      ["Perubahan pertama atas UU Keuangan Negara.", "Keliru. Perpres tidak mengubah undang-undang tersebut."],
      ["Pedoman Tata Naskah Dinas.", "Keliru. Bukan substansi Perpres ini."],
      ["Standar Biaya Masukan.", "Keliru. SBM ditetapkan melalui PMK."],
    ],
    answer: 0,
    source: "pbj",
    reference: "Judul dan status peraturan",
  },
  {
    id: 100,
    topic: "Keuangan & Pengadaan",
    difficulty: "Analitik",
    stem: "Harga Perkiraan Sendiri (HPS) dalam pengadaan pemerintah paling tepat dipahami sebagai…",
    options: [
      ["Perkiraan harga barang/jasa yang ditetapkan PPK dengan memperhitungkan biaya tidak langsung, keuntungan, dan PPN.", "Benar. HPS merupakan alat kewajaran harga yang disusun dan ditetapkan PPK."],
      ["Harga penawaran pemenang yang ditetapkan penyedia.", "Keliru. Penawaran penyedia berbeda dengan HPS."],
      ["Pagu anggaran yang selalu sama dengan nilai kontrak.", "Keliru. Pagu, HPS, dan nilai kontrak adalah konsep berbeda."],
      ["Harga tanpa pajak dan tanpa biaya tidak langsung.", "Keliru. Definisi HPS justru memperhitungkan unsur tersebut."],
    ],
    answer: 0,
    source: "pbj",
    reference: "Ketentuan umum — Harga Perkiraan Sendiri",
  },
];
