import type { QuestionSeed, QuizOption, Topic } from "./questions";

type SourceKey = Question["source"];
type Distractor = readonly [text: string, whyWrong: string];

function q(
  id: number,
  topic: Topic,
  stem: string,
  correct: string,
  whyCorrect: string,
  distractors: readonly Distractor[],
  source: SourceKey,
  reference: string,
): Question {
  const options: QuizOption[] = [
    [correct, `Benar. ${whyCorrect}`],
    ...distractors.map(
      ([text, whyWrong]) =>
        [text, `Keliru. ${whyWrong}`] as QuizOption,
    ),
  ];
  return {
    id,
    topic,
    difficulty: "Menjebak",
    stem,
    options,
    answer: 0,
    source,
    reference,
  };
}

export const supplementalQuestions: QuestionSeed[] = [
  q(
    101,
    "Manajemen Kinerja",
    "Urutan prinsip manajemen kinerja yang sama persis dengan KMK 127 Tahun 2026 adalah...",
    "Objektif, terukur, akuntabel, partisipatif, dan transparan.",
    "Kelima istilah tersebut dinyatakan dalam Diktum KEDUA.",
    [
      ["Objektif, terukur, adaptif, partisipatif, dan transparan.", "Kata ketiga diubah dari akuntabel menjadi adaptif."],
      ["Objektif, terarah, akuntabel, partisipatif, dan transparan.", "Kata kedua yang benar adalah terukur, bukan terarah."],
      ["Objektif, terukur, akuntabel, produktif, dan transparan.", "Kata keempat yang benar adalah partisipatif, bukan produktif."],
    ],
    "kinerja2026",
    "KMK 127 Tahun 2026, Diktum KEDUA",
  ),
  q(
    102,
    "Manajemen Kinerja",
    "Pasangan batas maksimum jumlah IKU pada UPK-One, UPK-Two, dan UPK-Three yang tepat adalah...",
    "25, 20, dan 15.",
    "Batas maksimum turun lima untuk tiap level: 25-20-15.",
    [
      ["25, 20, dan 10.", "Angka UPK-Three digeser dari 15 menjadi 10."],
      ["20, 15, dan 10.", "Ketiga angka digeser lima lebih rendah."],
      ["25, 15, dan 10.", "Batas UPK-Two dan UPK-Three seharusnya 20 dan 15."],
    ],
    "kinerja2026",
    "Materi Sosialisasi KMK 127/2026 - Ketentuan jumlah IKU",
  ),
  q(
    103,
    "Manajemen Kinerja",
    "Batas waktu penetapan Manual IKU setelah Perjanjian Kinerja ditetapkan adalah...",
    "Paling lambat 1 bulan setelah PK ditetapkan.",
    "Materi menetapkan batas satu bulan setelah PK.",
    [
      ["Paling lambat 15 hari kerja setelah PK ditetapkan.", "Batas 15 hari kerja muncul pada konteks penetapan PK baru setelah pelantikan, bukan Manual IKU."],
      ["Paling lambat 1 bulan sebelum PK ditetapkan.", "Arah waktunya terbalik; Manual IKU ditetapkan setelah PK."],
      ["Paling lambat 2 bulan setelah PK ditetapkan.", "Angka yang ditetapkan adalah satu bulan, bukan dua."],
    ],
    "kinerja2026",
    "Materi Sosialisasi KMK 127/2026 - Manual IKU",
  ),
  q(
    104,
    "Manajemen Kinerja",
    "Predikat NKO untuk X tepat sama dengan 110 adalah...",
    "Sangat Baik.",
    "Rentang Sangat Baik dirumuskan X lebih besar dari atau sama dengan 110.",
    [
      ["Baik.", "Predikat Baik hanya untuk 100 < X < 110, sehingga 110 tidak termasuk."],
      ["Cukup.", "Cukup berada pada 90 < X < 100."],
      ["Sangat Baik hanya jika X > 110.", "Tanda yang benar adalah ≥, bukan >."],
    ],
    "kinerja2026",
    "Materi Sosialisasi KMK 127/2026 - Predikat NKO",
  ),
  q(
    105,
    "Manajemen Kinerja",
    "Batas maksimal fully cascading antar-UPK secara vertikal adalah...",
    "Dua level ke bawah.",
    "Materi menetapkan fully cascading vertikal maksimal dua level.",
    [
      ["Satu level ke bawah.", "Satu level adalah pola normal, tetapi batas maksimal yang disebut adalah dua."],
      ["Tiga level ke bawah.", "Angka ini melebihi batas dua level."],
      ["Dua level ke atas.", "Arah cascading adalah dari level lebih tinggi ke lebih rendah."],
    ],
    "kinerja2026",
    "Materi Sosialisasi KMK 127/2026 - Cascading",
  ),
  q(
    106,
    "Manajemen Kinerja",
    "Perubahan jenis konsolidasi periode untuk suatu IKU dapat dilakukan...",
    "Maksimal sekali dalam setahun.",
    "Ketentuan perubahan Manual IKU membatasi perubahan jenis konsolidasi satu kali setahun.",
    [
      ["Maksimal sekali dalam satu semester.", "Satu semester lebih sering daripada batas yang ditetapkan."],
      ["Maksimal dua kali dalam setahun.", "Batasnya satu kali, bukan dua."],
      ["Setiap triwulan sepanjang target belum tercapai.", "Ketentuan tidak membuka perubahan setiap triwulan."],
    ],
    "kinerja2026",
    "Materi Sosialisasi KMK 127/2026 - Perubahan Manual IKU",
  ),
  q(
    107,
    "Disiplin & Kepegawaian",
    "Jumlah jam kerja reguler DJBC per minggu dan flexy time yang tepat adalah...",
    "42 jam 45 menit per minggu dan flexy time 90 menit.",
    "Kedua angka itu ditampilkan bersama pada materi jam kerja DJBC.",
    [
      ["42 jam 30 menit per minggu dan flexy time 90 menit.", "Jumlah mingguannya kurang 15 menit."],
      ["42 jam 45 menit per minggu dan flexy time 60 menit.", "Flexy time seharusnya 90 menit."],
      ["37 jam 30 menit per minggu dan flexy time 90 menit.", "Jumlah jam kerja mingguan bukan 37 jam 30 menit."],
    ],
    "sdmAdmin",
    "Materi SDM - Ketentuan Jam Kerja Pegawai",
  ),
  q(
    108,
    "Disiplin & Kepegawaian",
    "Core/collaborative hour pada jam kerja reguler DJBC berada pada rentang...",
    "09.00 sampai dengan 15.30.",
    "Rentang inti kolaborasi ditunjukkan 09.00-15.30.",
    [
      ["08.30 sampai dengan 15.30.", "Waktu mulai digeser 30 menit lebih awal."],
      ["09.00 sampai dengan 16.00.", "Waktu akhir digeser 30 menit lebih lambat."],
      ["09.30 sampai dengan 15.00.", "Kedua ujung rentang digeser 30 menit."],
    ],
    "sdmAdmin",
    "Materi SDM - Jam Kerja DJBC",
  ),
  q(
    109,
    "Disiplin & Kepegawaian",
    "Konversi tidak mengisi presensi masuk atau pulang, serta akumulasi menjadi satu hari tidak masuk, adalah...",
    "3 jam 45 menit; akumulasi 7 jam 30 menit menjadi 1 hari.",
    "Satu presensi yang hilang dihitung 3:45 dan dua kali akumulasi menjadi 7:30.",
    [
      ["3 jam 30 menit; akumulasi 7 jam menjadi 1 hari.", "Kedua angka dikurangi 15 dan 30 menit."],
      ["3 jam 45 menit; akumulasi 7 jam 45 menit menjadi 1 hari.", "Ambang akumulasi yang benar 7:30."],
      ["4 jam; akumulasi 8 jam menjadi 1 hari.", "Materi tidak membulatkan durasi menjadi empat dan delapan jam."],
    ],
    "sdmAdmin",
    "Materi SDM - Akumulasi Pelanggaran Jam Kerja",
  ),
  q(
    110,
    "Disiplin & Kepegawaian",
    "Syarat masa kerja dan hak cuti tahunan yang tepat adalah...",
    "Bekerja paling kurang 1 tahun terus-menerus; hak 12 hari kerja.",
    "Materi menggabungkan syarat satu tahun dan hak 12 hari kerja.",
    [
      ["Bekerja paling kurang 1 tahun terus-menerus; hak 12 hari kalender.", "Satuan hak dasarnya hari kerja, bukan hari kalender."],
      ["Bekerja paling kurang 2 tahun terus-menerus; hak 12 hari kerja.", "Syarat masa kerjanya satu tahun."],
      ["Bekerja paling kurang 1 tahun terus-menerus; hak 14 hari kerja.", "Jumlah haknya 12, bukan 14 hari kerja."],
    ],
    "sdmAdmin",
    "Materi SDM - Ketentuan Pengajuan Cuti Tahunan",
  ),
  q(
    111,
    "Disiplin & Kepegawaian",
    "Formula CLTN karena alasan pribadi dan mendesak yang benar adalah...",
    "Masa kerja minimal 5 tahun; maksimal 3 tahun; perpanjangan maksimal 1 tahun.",
    "Urutan angka yang tepat adalah 5-3-1.",
    [
      ["Masa kerja minimal 5 tahun; maksimal 2 tahun; perpanjangan maksimal 1 tahun.", "Durasi awal seharusnya tiga tahun."],
      ["Masa kerja minimal 3 tahun; maksimal 3 tahun; perpanjangan maksimal 1 tahun.", "Masa kerja minimum seharusnya lima tahun."],
      ["Masa kerja minimal 5 tahun; maksimal 3 tahun; perpanjangan maksimal 2 tahun.", "Perpanjangan dibatasi satu tahun."],
    ],
    "sdmAdmin",
    "Materi SDM - Cuti di Luar Tanggungan Negara",
  ),
  q(
    112,
    "Disiplin & Kepegawaian",
    "Pasangan syarat sisa masa kerja untuk Tugas Belajar Dibiayai yang diberhentikan dan tidak diberhentikan adalah...",
    "3n dan 2n.",
    "Syarat sisa masa kerja: diberhentikan 3n, tidak diberhentikan 2n.",
    [
      ["2n dan 1n.", "Ini pasangan ikatan dinas setelah studi, bukan syarat sisa masa kerja."],
      ["2n dan 3n.", "Urutan status diberhentikan dan tidak diberhentikan dibalik."],
      ["3n dan 1n.", "Angka status tidak diberhentikan seharusnya 2n."],
    ],
    "sdmDevelopment",
    "Materi Pengembangan SDM - Persyaratan TB Dibiayai",
  ),
  q(
    113,
    "Disiplin & Kepegawaian",
    "Pasangan masa ikatan dinas setelah TB Dibiayai untuk status diberhentikan dan tidak diberhentikan adalah...",
    "2n dan 1n.",
    "Ikatan dinas lebih pendek satu n dibanding syarat sisa masa kerja.",
    [
      ["3n dan 2n.", "Ini pasangan syarat sisa masa kerja."],
      ["1n dan 2n.", "Urutan kedua status dibalik."],
      ["2n dan 2n.", "Status tidak diberhentikan memiliki ikatan 1n."],
    ],
    "sdmDevelopment",
    "Materi Pengembangan SDM - Penempatan Kembali dan Ikatan Dinas",
  ),
  q(
    114,
    "Disiplin & Kepegawaian",
    "Pemantauan dan evaluasi pengembangan SDM dilaporkan dengan frekuensi...",
    "Pemantauan per semester kepada Sekjen; evaluasi per tahun kepada Menkeu melalui Sekjen.",
    "Materi membedakan pemantauan semesteran dan evaluasi tahunan.",
    [
      ["Pemantauan per tahun kepada Sekjen; evaluasi per semester kepada Menkeu.", "Frekuensi keduanya dibalik."],
      ["Pemantauan per triwulan; evaluasi per semester.", "Materi menetapkan semester dan tahun, bukan triwulan dan semester."],
      ["Pemantauan dan evaluasi keduanya per semester kepada Sekjen.", "Evaluasi tahunan ditujukan kepada Menkeu melalui Sekjen."],
    ],
    "sdmDevelopment",
    "Materi Pengembangan SDM - Monev",
  ),
  q(
    115,
    "Keuangan & Pengadaan",
    "Tiga pilar sistem penganggaran yang tepat adalah...",
    "Penganggaran Terpadu, Penganggaran Berbasis Kinerja, dan Kerangka Pengeluaran Jangka Menengah.",
    "Ketiganya dinyatakan sebagai tiga pilar dalam materi.",
    [
      ["Penganggaran Terpadu, Penganggaran Berbasis Kegiatan, dan Kerangka Pengeluaran Jangka Menengah.", "Istilah yang benar berbasis kinerja, bukan berbasis kegiatan."],
      ["Penganggaran Terpadu, Penganggaran Berbasis Kinerja, dan Kerangka Penerimaan Jangka Menengah.", "Istilah yang benar kerangka pengeluaran."],
      ["Penganggaran Terpisah, Penganggaran Berbasis Kinerja, dan Kerangka Pengeluaran Jangka Menengah.", "Pilar pertama adalah terpadu, bukan terpisah."],
    ],
    "budget2026",
    "Materi Pengelolaan Anggaran - Tiga Pilar",
  ),
  q(
    116,
    "Keuangan & Pengadaan",
    "Kerangka Pengeluaran Jangka Menengah memperhatikan implikasi anggaran dalam periode...",
    "3 tahun ke depan.",
    "Materi secara eksplisit menyebut periode tiga tahun ke depan.",
    [
      ["2 tahun ke depan.", "Horizon digeser satu tahun lebih pendek."],
      ["4 tahun ke depan.", "Horizon digeser satu tahun lebih panjang."],
      ["5 tahun ke depan.", "Angka lima tidak digunakan pada rumusan KPJM ini."],
    ],
    "budget2026",
    "Materi Pengelolaan Anggaran - KPJM",
  ),
  q(
    117,
    "Keuangan & Pengadaan",
    "Pejabat yang menetapkan PPK dan PPSPM pada satuan kerja adalah...",
    "Kuasa Pengguna Anggaran.",
    "Penetapan PPK dan PPSPM termasuk tugas dan wewenang KPA.",
    [
      ["Pejabat Pembuat Komitmen.", "PPK tidak menetapkan dirinya sendiri dan PPSPM."],
      ["Pejabat Penandatangan SPM.", "PPSPM ditetapkan oleh KPA."],
      ["Bendahara Pengeluaran.", "Bendahara tidak memiliki kewenangan penetapan kedua pejabat tersebut."],
    ],
    "budget2026",
    "Materi Pengelolaan Anggaran - KPA",
  ),
  q(
    118,
    "Keuangan & Pengadaan",
    "Pasangan dokumen dan pejabat penerbit yang tepat adalah...",
    "PPK menerbitkan SPP; PPSPM menerbitkan SPM.",
    "PPK mengajukan permintaan pembayaran melalui SPP, lalu PPSPM menguji dan menerbitkan SPM.",
    [
      ["PPK menerbitkan SPM; PPSPM menerbitkan SPP.", "Dokumen kedua pejabat ditukar."],
      ["KPA menerbitkan SPP; PPK menerbitkan SPM.", "Kewenangan penerbitan keduanya tidak tepat."],
      ["PPSPM menerbitkan SPP dan SPM sekaligus.", "PPSPM menerima/menguji SPP, bukan menerbitkannya."],
    ],
    "budget2026",
    "Materi Pengelolaan Anggaran - PPK dan PPSPM",
  ),
  q(
    119,
    "Keuangan & Pengadaan",
    "KPA dianggap berhalangan ketika pejabat definitif tidak dapat bertugas lebih dari...",
    "45 hari kalender.",
    "Materi menyebut lebih dari 45 hari kalender.",
    [
      ["45 hari kerja.", "Satuannya kalender, bukan hari kerja."],
      ["30 hari kalender.", "Ambang waktunya 45 hari."],
      ["60 hari kalender.", "Angka 60 melebihi ambang yang ditetapkan."],
    ],
    "budget2026",
    "Materi Pengelolaan Anggaran - Pelaksana Tugas KPA",
  ),
  q(
    120,
    "Keuangan & Pengadaan",
    "Tanggung jawab materiil KPA mencakup...",
    "Penggunaan anggaran dan keluaran yang dihasilkan atas beban anggaran negara.",
    "Materi membedakan tanggung jawab materiil dari tanggung jawab formil.",
    [
      ["Pelaksanaan tugas dan wewenang KPA saja.", "Itu rumusan tanggung jawab formil."],
      ["Kebenaran data supplier dan data kontrak saja.", "Itu bagian tanggung jawab PPK, bukan rumusan materiil KPA."],
      ["Pengujian SPP dan penerbitan SPM saja.", "Itu tugas PPSPM, bukan keseluruhan tanggung jawab materiil KPA."],
    ],
    "budget2026",
    "Materi Pengelolaan Anggaran - Tanggung Jawab KPA",
  ),
  q(
    121,
    "Umum, Rumah Tangga & BMN",
    "Definisi BMN yang lengkap mencakup...",
    "Barang yang dibeli/diperoleh atas beban APBN atau berasal dari perolehan lain yang sah.",
    "Definisi mencakup dua jalur perolehan tersebut.",
    [
      ["Barang yang dibeli hanya dari belanja modal APBN.", "BMN tidak terbatas pada belanja modal."],
      ["Barang yang dibeli atas beban APBN dan wajib berupa aset tetap.", "BMN juga dapat berupa persediaan dan aset lainnya."],
      ["Barang milik pemerintah yang hanya berasal dari hibah.", "Hibah hanya salah satu bentuk perolehan lain yang sah."],
    ],
    "bmn2026",
    "Bahan Siklus Pengelolaan BMN - Lingkup BMN",
  ),
  q(
    122,
    "Umum, Rumah Tangga & BMN",
    "RKBMN merupakan dokumen perencanaan untuk periode dan horizon kebutuhan...",
    "Periode dokumen 1 tahun; kebutuhan untuk diadakan 2 tahun ke depan.",
    "Materi membedakan periode dokumen dari horizon kebutuhan T-2.",
    [
      ["Periode dokumen 2 tahun; kebutuhan untuk diadakan 1 tahun ke depan.", "Kedua angka dan fungsinya ditukar."],
      ["Periode dokumen 1 tahun; kebutuhan untuk diadakan 3 tahun ke depan.", "Horizon kebutuhan adalah dua tahun, bukan tiga."],
      ["Periode dokumen 3 tahun; kebutuhan untuk diadakan 2 tahun ke depan.", "Periode dokumennya satu tahun."],
    ],
    "bmn2026",
    "Bahan Siklus Pengelolaan BMN - RKBMN",
  ),
  q(
    123,
    "Umum, Rumah Tangga & BMN",
    "Ambang nilai usulan paket belanja modal untuk project selection adalah...",
    "Di atas Rp500.000.000.",
    "Materi menggunakan frasa di atas Rp500 juta.",
    [
      ["Paling sedikit Rp500.000.000.", "Frasa paling sedikit memasukkan tepat Rp500 juta, sedangkan materi menyebut di atas."],
      ["Di atas Rp100.000.000.", "Rp100 juta muncul pada objek pemeliharaan BMN tertentu."],
      ["Di atas Rp5.000.000.000.", "Nilainya bertambah satu digit dari ambang yang disebut."],
    ],
    "bmn2026",
    "Bahan Siklus Pengelolaan BMN - Project Selection",
  ),
  q(
    124,
    "Umum, Rumah Tangga & BMN",
    "Ambang nilai perolehan per satuan BMN sebagai objek RKBMN pemeliharaan adalah...",
    "Lebih dari Rp100.000.000.",
    "Materi menyebut BMN dengan nilai perolehan per satuan lebih dari Rp100 juta.",
    [
      ["Paling sedikit Rp100.000.000.", "Frasa paling sedikit berbeda dari lebih dari."],
      ["Lebih dari Rp500.000.000.", "Rp500 juta adalah angka project selection."],
      ["Lebih dari Rp100.000.000 per paket.", "Basisnya per satuan BMN, bukan per paket."],
    ],
    "bmn2026",
    "Bahan Siklus Pengelolaan BMN - RKBMN Pemeliharaan",
  ),
  q(
    125,
    "Umum, Rumah Tangga & BMN",
    "Urutan tahap project selection dari T-3 sampai T-1 adalah...",
    "Identifikasi Awal, Update Usulan, Pengusulan pada RKA-K/L.",
    "Ketiga tahap tersebut mengikuti T-3, T-2, dan T-1.",
    [
      ["Update Usulan, Identifikasi Awal, Pengusulan pada RKA-K/L.", "Dua tahap pertama ditukar."],
      ["Identifikasi Awal, Pengusulan pada RKA-K/L, Update Usulan.", "Tahap pengusulan seharusnya terakhir."],
      ["Identifikasi Awal, Reviu APIP, Pengusulan pada DIPA.", "Reviu APIP dan DIPA bukan nama tiga tahap project selection."],
    ],
    "bmn2026",
    "Bahan Siklus Pengelolaan BMN - Tahap Project Selection",
  ),
  q(
    126,
    "Keuangan & Pengadaan",
    "Pemetaan tipologi PPK yang benar adalah...",
    "Tipe A kompleks, Tipe B umum/lazim, Tipe C sederhana.",
    "Huruf A-B-C dipetakan dari kompleks ke sederhana.",
    [
      ["Tipe A sederhana, Tipe B umum/lazim, Tipe C kompleks.", "Tipe A dan C dibalik."],
      ["Tipe A kompleks, Tipe B sederhana, Tipe C umum/lazim.", "Tipe B dan C ditukar."],
      ["Tipe A umum/lazim, Tipe B kompleks, Tipe C sederhana.", "Tipe A dan B ditukar."],
    ],
    "bmn2026",
    "Bahan Siklus Pengelolaan BMN - Tipologi PPK",
  ),
  q(
    127,
    "Layanan Informasi",
    "Nomor surat edaran yang menjadi rujukan definisi layanan informasi DJBC dalam materi Bravo adalah...",
    "SE-15/BC/2025.",
    "Materi menyebut SE-15/BC/2025 untuk definisi layanan informasi.",
    [
      ["SE-14/BC/2025.", "SE-14/BC/2025 berkaitan dengan komunikasi internal."],
      ["SE-16/BC/2020.", "SE-16/BC/2020 disebut pada fungsi aplikasi SPLIT."],
      ["SE-15/BC/2020.", "Nomornya 15, tetapi tahunnya seharusnya 2025."],
    ],
    "bravo",
    "Layanan Informasi Bravo - Definisi Layanan Informasi",
  ),
  q(
    128,
    "Layanan Informasi",
    "Jumlah saluran layanan informasi kepabeanan dan cukai yang dicantumkan dalam materi adalah...",
    "7 saluran.",
    "Daftar bernomor memuat tujuh saluran.",
    [
      ["6 saluran.", "Jalur resmi lainnya merupakan butir ketujuh."],
      ["8 saluran.", "Materi tidak memberi nomor kedelapan."],
      ["5 saluran.", "Angka ini hanya memotong dua saluran terakhir."],
    ],
    "bravo",
    "Layanan Informasi Bravo - Saluran Layanan",
  ),
  q(
    129,
    "Layanan Informasi",
    "Dasar yang disebut pada fungsi database peraturan Aplikasi SPLIT adalah...",
    "SE-16/BC/2020.",
    "Materi menempatkan SE-16/BC/2020 pada fungsi pencarian peraturan SPLIT.",
    [
      ["SE-15/BC/2025.", "Aturan ini menjadi rujukan layanan informasi, bukan nomor yang ditampilkan pada fungsi SPLIT."],
      ["SE-14/BC/2025.", "Ini terkait komunikasi internal."],
      ["SE-16/BC/2025.", "Nomornya benar, tetapi tahunnya digeser dari 2020 ke 2025."],
    ],
    "bravo",
    "Layanan Informasi Bravo - Fungsi Aplikasi SPLIT",
  ),
  q(
    130,
    "Layanan Informasi",
    "Bobot maksimum Attitude, Skill, dan Knowledge pada layanan inbound adalah...",
    "30, 45, dan 25.",
    "Rumus total pada materi adalah 30 + 45 + 25 = 100.",
    [
      ["30, 25, dan 45.", "Bobot Skill dan Knowledge ditukar."],
      ["25, 45, dan 30.", "Bobot Attitude dan Knowledge ditukar."],
      ["30, 45, dan 45.", "Jumlahnya menjadi 120 dan tidak sesuai total maksimum 100."],
    ],
    "bravo",
    "Layanan Informasi Bravo - Parameter Penilaian Inbound",
  ),
  q(
    131,
    "Layanan Informasi",
    "Standar waktu hold sebelum meminta kesediaan untuk tambahan waktu adalah...",
    "3,5 menit.",
    "Materi menetapkan standar hold time tiga setengah menit.",
    [
      ["3 menit.", "Kurang setengah menit dari standar."],
      ["4,5 menit.", "Lebih satu menit dari standar."],
      ["5 menit.", "Materi tidak membulatkan menjadi lima menit."],
    ],
    "bravo",
    "Layanan Informasi Bravo - Mengelola Hold Time",
  ),
  q(
    132,
    "Layanan Informasi",
    "Komposisi skor maksimum penilaian kualitas e-mail yang tepat adalah...",
    "25 + 15 + 35 + 10 + 15 = 100.",
    "Komponen waktu, sistematika, ketepatan, dasar hukum, dan atribut berjumlah 100.",
    [
      ["25 + 15 + 30 + 15 + 15 = 100.", "Bobot ketepatan dan dasar hukum digeser menjadi 30 dan 15."],
      ["25 + 10 + 35 + 15 + 15 = 100.", "Bobot sistematika dan dasar hukum ditukar."],
      ["20 + 15 + 35 + 10 + 15 = 95.", "Bobot waktu seharusnya 25 sehingga total 100."],
    ],
    "bravo",
    "Layanan Informasi Bravo - Penilaian Kualitas E-mail",
  ),
  q(
    133,
    "AI dalam Probis",
    "Kedudukan keluaran AI dalam analisis proses bisnis kepabeanan dan cukai yang paling tepat adalah...",
    "Bahan bantu yang wajib diverifikasi terhadap fakta, data, dan sumber resmi sebelum digunakan.",
    "AI mempercepat analisis, tetapi tidak mengambil alih validasi maupun akuntabilitas.",
    [
      ["Sumber hukum yang dapat langsung menggantikan JDIH.", "AI bukan sumber hukum dan dapat menghasilkan rujukan yang keliru."],
      ["Keputusan final otomatis sepanjang jawabannya konsisten.", "Konsistensi bahasa tidak membuktikan kebenaran atau kewenangan."],
      ["Pendapat ahli yang tidak memerlukan pemeriksaan ulang.", "Keluaran tetap perlu uji silang dan human review."],
    ],
    "aiProbis",
    "Sharing Session AI - Human in the Loop",
  ),
  q(
    134,
    "AI dalam Probis",
    "Urutan kontrol yang paling aman saat AI menyebut nomor dan isi peraturan adalah...",
    "Periksa nomor, tahun, judul, status berlaku, lalu cocokkan bunyi ketentuan pada sumber resmi.",
    "Kelima pemeriksaan mencegah rujukan palsu, kedaluwarsa, atau salah konteks.",
    [
      ["Periksa judul saja karena nomor dan tahun dapat disimpulkan.", "Nomor dan tahun harus diverifikasi secara mandiri."],
      ["Cocokkan ringkasan AI dengan jawaban AI lain.", "Dua keluaran AI bukan pengganti sumber resmi."],
      ["Gunakan peraturan pertama yang muncul tanpa mengecek statusnya.", "Aturan dapat telah diubah, dicabut, atau tidak relevan."],
    ],
    "aiProbis",
    "Sharing Session AI - Verifikasi Rujukan",
  ),
  q(
    135,
    "AI dalam Probis",
    "Prinsip minimisasi data saat menyusun prompt berarti...",
    "Hanya memasukkan data minimum yang relevan untuk tujuan yang sah dan jelas.",
    "Minimisasi membatasi volume dan jenis data sesuai kebutuhan.",
    [
      ["Memasukkan seluruh dokumen agar konteks selalu lengkap.", "Kelengkapan berlebihan dapat membuka data yang tidak diperlukan."],
      ["Menghapus nama tetapi mempertahankan seluruh pengenal unik.", "Kombinasi pengenal lain masih dapat mengidentifikasi subjek."],
      ["Menggunakan kanal apa pun selama data dikirim singkat.", "Panjang prompt tidak menggantikan kontrol kanal dan klasifikasi."],
    ],
    "aiProbis",
    "Sharing Session AI - Perlindungan Data",
  ),
  q(
    136,
    "AI dalam Probis",
    "Pemisahan yang paling membantu mendeteksi halusinasi AI dalam nota analisis adalah...",
    "Pisahkan kutipan fakta sumber, analisis, dan asumsi; beri rujukan pada fakta yang dapat diuji.",
    "Struktur tersebut membuat klaim dapat ditelusuri dan diuji silang.",
    [
      ["Gabungkan fakta dan asumsi agar narasi lebih singkat.", "Penggabungan menyulitkan pembaca membedakan klaim terverifikasi."],
      ["Hilangkan rujukan agar analisis tampak mandiri.", "Tanpa rujukan, klaim faktual lebih sulit diaudit."],
      ["Gunakan gaya bahasa tegas untuk meningkatkan kepastian.", "Nada tegas tidak meningkatkan akurasi."],
    ],
    "aiProbis",
    "Sharing Session AI - Traceability",
  ),
];
